import Link from 'next/link';
import { CalendarDays, ChevronDown, ChevronRight, ImageIcon, List, MapPin, Search } from 'lucide-react';
import { db } from '@/db';
import { assets, exifMetadata, locations, photos } from '@/db/schema';
import { and, asc, count, desc, eq, isNotNull, isNull, like, or, sql } from 'drizzle-orm';
import { alias } from 'drizzle-orm/sqlite-core';

type SearchParams = { date?: string; q?: string; status?: string; orientation?: string; location?: string; sort?: string; page?: string; view?: string };
const daySql = sql<string>`strftime('%Y-%m-%d', ${photos.capturedAt}, 'unixepoch', '+7 hours')`;
const formatDay = new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'long', year: 'numeric', weekday: 'long', timeZone: 'Asia/Jakarta' });
const monthFormatter = new Intl.DateTimeFormat('id-ID', { month: 'long', timeZone: 'UTC' });
const localDay = (date: Date | null) => date ? new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'Asia/Jakarta' }).format(date) : 'undated';
const validDay = (value: string | undefined) => { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T12:00:00+07:00`); return !Number.isNaN(parsed.getTime()) && localDay(parsed) === value; };
const labelDay = (key: string) => key === 'undated' ? 'Tanpa tanggal' : formatDay.format(new Date(`${key}T12:00:00+07:00`));
const monthLabel = (key: string) => monthFormatter.format(new Date(`${key}-01T00:00:00Z`));

export default async function TimelinePage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const query = await searchParams;
  const active = isNull(photos.deletedAt);
  const days = db.select({ day: daySql, value: count() }).from(photos).where(and(active, isNotNull(photos.capturedAt))).groupBy(daySql).orderBy(desc(daySql)).all();
  const undated = db.select({ value: count() }).from(photos).where(and(active, isNull(photos.capturedAt))).get()?.value ?? 0;
  const totalArchive = days.reduce((sum, row) => sum + row.value, undated);
  const date = query.date === 'all' || query.date === 'undated' || validDay(query.date) ? query.date! : days[0]?.day ?? (undated ? 'undated' : 'all');
  const q = (query.q ?? '').trim().slice(0, 100);
  const status = ['Ready', 'Need Review', 'Private'].includes(query.status ?? '') ? query.status : '';
  const orientation = ['landscape', 'portrait', 'square'].includes(query.orientation ?? '') ? query.orientation : '';
  const locationFilter = query.location === 'yes' || query.location === 'no' ? query.location : '';
  const sort = query.sort === 'oldest' ? 'oldest' : 'newest';
  const view = query.view === 'list' ? 'list' : 'grid';
  const page = Math.max(1, Math.min(500, Number.parseInt(query.page ?? '1', 10) || 1));
  const original = alias(assets, 'original_asset');
  const thumb = alias(assets, 'thumbnail_asset');
  const scope = date === 'all' ? undefined : date === 'undated' ? isNull(photos.capturedAt) : eq(daySql, date);
  const search = q ? or(like(photos.filename, `%${q}%`), like(locations.label, `%${q}%`), like(exifMetadata.camera, `%${q}%`)) : undefined;
  const orientationWhere = orientation === 'landscape' ? sql`${original.width} > ${original.height}` : orientation === 'portrait' ? sql`${original.width} < ${original.height}` : orientation === 'square' ? sql`${original.width} = ${original.height}` : undefined;
  const locationWhere = locationFilter === 'yes' ? isNotNull(locations.id) : locationFilter === 'no' ? isNull(locations.id) : undefined;
  const where = and(active, scope, search, status ? eq(photos.status, status) : undefined, orientationWhere, locationWhere);
  const base = db.select({ id: photos.id }).from(photos).leftJoin(original, and(eq(original.photoId, photos.id), eq(original.type, 'original'))).leftJoin(locations, eq(locations.photoId, photos.id)).leftJoin(exifMetadata, eq(exifMetadata.photoId, photos.id)).where(where);
  const total = db.select({ value: count() }).from(base.as('filtered_photos')).get()?.value ?? 0;
  const items = db.select({ id: photos.id, filename: photos.filename, capturedAt: photos.capturedAt, status: photos.status, thumbnailId: thumb.id, location: locations.label, live: sql<number>`exists(select 1 from live_photos lp join live_sessions ls on ls.id = lp.live_session_id where lp.photo_id = ${photos.id} and ls.status = 'Active')`, issueCode: sql<string | null>`(select i.code from issue_page_photos ipp join issue_pages ip on ip.id = ipp.page_id join issues i on i.id = ip.issue_id where ipp.photo_id = ${photos.id} limit 1)` }).from(photos).leftJoin(original, and(eq(original.photoId, photos.id), eq(original.type, 'original'))).leftJoin(thumb, and(eq(thumb.photoId, photos.id), eq(thumb.type, 'thumbnail'))).leftJoin(locations, eq(locations.photoId, photos.id)).leftJoin(exifMetadata, eq(exifMetadata.photoId, photos.id)).where(where).orderBy(sort === 'oldest' ? asc(photos.capturedAt) : desc(photos.capturedAt), sort === 'oldest' ? asc(sql`photos.rowid`) : desc(sql`photos.rowid`)).limit(page * 24).all();
  const groups = new Map<string, typeof items>();
  for (const item of items) { const key = localDay(item.capturedAt); groups.set(key, [...(groups.get(key) ?? []), item]); }
  const tree = new Map<string, Map<string, { day: string; value: number }[]>>();
  for (const item of days) { const year = item.day.slice(0, 4), month = item.day.slice(0, 7); if (!tree.has(year)) tree.set(year, new Map()); const months = tree.get(year)!; months.set(month, [...(months.get(month) ?? []), item]); }
  const filters = { ...(q ? { q } : {}), ...(status ? { status } : {}), ...(orientation ? { orientation } : {}), ...(locationFilter ? { location: locationFilter } : {}), ...(sort !== 'newest' ? { sort } : {}), ...(view !== 'grid' ? { view } : {}) };
  const scopeHref = (selected: string) => `/timeline?${new URLSearchParams({ ...filters, date: selected })}`;
  const pageHref = `/timeline?${new URLSearchParams({ ...filters, date, page: String(page + 1) })}`;
  return <div className="mx-auto grid max-w-[1650px] gap-6 pb-8 lg:grid-cols-[215px_minmax(0,1fr)]">
    <aside className="border-r border-[#dce2dd] pr-4"><h2 className="mb-4 text-xs font-bold tracking-widest">LINIMASA</h2><Link href={scopeHref('all')} className={`inline-block rounded border px-3 py-2 text-xs font-semibold ${date === 'all' ? 'border-[#116a5c] bg-[#e5f2ec] text-[#116a5c]' : 'border-[#d6dfd9] bg-white'}`}>SEMUA ({totalArchive})</Link><form action="/timeline" className="mt-4"><label htmlFor="jump-date" className="sr-only">Lompat ke tanggal</label><input id="jump-date" type="date" name="date" defaultValue={/^\d{4}-\d{2}-\d{2}$/.test(date) ? date : ''} className="w-full rounded border border-[#d6dfd9] bg-white px-2 py-2 text-xs"/><button className="mt-2 w-full rounded border border-[#116a5c] py-1.5 text-xs text-[#116a5c]">Lompat ke tanggal</button></form><nav aria-label="Tanggal arsip" className="mt-5 max-h-[65vh] space-y-2 overflow-y-auto pr-1">{[...tree].map(([year, months]) => { const yearCount = [...months.values()].flat().reduce((sum, item) => sum + item.value, 0); return <details key={year} open={date.startsWith(year)} className="group"><summary className="flex cursor-pointer items-center gap-2 py-1 text-sm font-semibold"><ChevronRight size={14} className="group-open:rotate-90"/><span className="h-2 w-2 rounded-full bg-[#116a5c]"/>{year} <span className="font-normal text-[#73817f]">({yearCount})</span></summary><div className="ml-5 border-l border-[#d6dfd9] pl-3">{[...months].map(([month, monthDays]) => <details key={month} open={date.startsWith(month)} className="group/month"><summary className="flex cursor-pointer items-center gap-2 py-1 text-xs"><ChevronRight size={13} className="group-open/month:rotate-90"/>{monthLabel(month)} <span className="text-[#73817f]">({monthDays.reduce((sum, item) => sum + item.value, 0)})</span></summary><div className="ml-3 border-l border-[#d6dfd9] pl-2">{monthDays.map(item => <Link key={item.day} href={scopeHref(item.day)} aria-current={date === item.day ? 'date' : undefined} className={`block rounded px-2 py-1.5 text-xs ${date === item.day ? 'bg-[#e4f0e9] font-semibold text-[#116a5c]' : 'hover:bg-[#f0f4f1]'}`}>{Number(item.day.slice(8))} {monthLabel(month).slice(0, 3)} <span className="text-[#73817f]">({item.value})</span></Link>)}</div></details>)}</div></details>; })}{undated > 0 && <Link href={scopeHref('undated')} className={`block rounded px-2 py-2 text-xs ${date === 'undated' ? 'bg-[#e4f0e9] font-semibold text-[#116a5c]' : ''}`}>Tanpa tanggal ({undated})</Link>}</nav></aside>
    <div className="min-w-0 space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight">Timeline Fotografi</h1><p className="text-sm text-[#647579]">Jelajahi arsip berdasarkan waktu pengambilan.</p></div><div className="flex gap-2"><Link href={`/timeline?${new URLSearchParams({ ...filters, date, view: 'grid' })}`} aria-label="Tampilan grid" className={`rounded border p-2 ${view === 'grid' ? 'border-[#116a5c] bg-[#116a5c] text-white' : 'border-[#d6dfd9] bg-white'}`}><ImageIcon size={18}/></Link><Link href={`/timeline?${new URLSearchParams({ ...filters, date, view: 'list' })}`} aria-label="Tampilan daftar" className={`rounded border p-2 ${view === 'list' ? 'border-[#116a5c] bg-[#116a5c] text-white' : 'border-[#d6dfd9] bg-white'}`}><List size={18}/></Link></div></div>
      <form action="/timeline" className="flex flex-wrap gap-2"><input type="hidden" name="date" value={date}/><label className="relative min-w-42 flex-1"><span className="sr-only">Cari foto</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#71817e]" size={17}/><input type="search" name="q" defaultValue={q} placeholder="Cari filename, lokasi, kamera..." className="h-10 w-full rounded border border-[#d6dfd9] bg-white pl-9 pr-3 text-sm"/></label><select name="status" aria-label="Filter status" defaultValue={status} className="h-10 rounded border border-[#d6dfd9] bg-white px-2 text-xs"><option value="">Semua status</option><option value="Ready">Siap</option><option value="Need Review">Perlu diperiksa</option><option value="Private">Private</option></select><select name="orientation" aria-label="Filter orientasi" defaultValue={orientation} className="h-10 rounded border border-[#d6dfd9] bg-white px-2 text-xs"><option value="">Semua orientasi</option><option value="landscape">Landscape</option><option value="portrait">Portrait</option><option value="square">Persegi</option></select><select name="location" aria-label="Filter lokasi" defaultValue={locationFilter} className="h-10 rounded border border-[#d6dfd9] bg-white px-2 text-xs"><option value="">Semua lokasi</option><option value="yes">Memiliki lokasi</option><option value="no">Tanpa lokasi</option></select><select name="sort" aria-label="Urutan" defaultValue={sort} className="h-10 rounded border border-[#d6dfd9] bg-white px-2 text-xs"><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select><button className="h-10 rounded bg-[#116a5c] px-4 text-xs font-semibold text-white">Terapkan</button>{(q || status || orientation || locationFilter || sort !== 'newest') && <Link href={`/timeline?date=${date}`} className="self-center text-xs text-[#116a5c] underline">Hapus filter</Link>}</form>
      <p className="text-sm"><strong>{total.toLocaleString('id-ID')} foto</strong> <span className="text-[#778683]">· {date === 'all' ? 'Semua tanggal' : labelDay(date)}</span></p>
      {items.length ? [...groups].map(([key, group]) => <section key={key}><div className="mb-4 flex items-center gap-4"><h2 className="shrink-0 text-2xl font-bold">{labelDay(key)}</h2><div className="h-px flex-1 bg-[#cbd5d0]"/></div><div className={view === 'list' ? 'space-y-3' : 'grid grid-cols-2 gap-x-4 gap-y-5 md:grid-cols-3 xl:grid-cols-4'}>{group.map(photo => <Link key={photo.id} href={`/photos/${photo.id}`} className={`group min-w-0 ${view === 'list' ? 'flex items-center gap-4 rounded border border-[#d9e0dc] bg-white p-2' : ''}`}><div className={`overflow-hidden rounded bg-[#e8eeeb] ring-[#116a5c] group-hover:ring-2 ${view === 'list' ? 'h-24 w-36 shrink-0' : 'aspect-[1.7] w-full'}`}>{photo.thumbnailId ? <img src={`/api/assets/${photo.thumbnailId}`} alt="" loading="lazy" className="h-full w-full object-cover"/> : <div className="flex h-full items-center justify-center text-[#91a39d]"><ImageIcon size={30}/></div>}</div><div className="min-w-0 pt-2 text-xs"><div className="flex items-center justify-between gap-2"><span className="truncate font-mono">{photo.capturedAt?.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Jakarta' }) ?? 'Waktu belum ada'} · {photo.filename}</span>{photo.live ? <span className="rounded bg-[#176b5d] px-2 py-0.5 text-[10px] text-white">LIVE</span> : photo.issueCode ? <span className="rounded bg-[#e6ece9] px-2 py-0.5 text-[10px]">{photo.issueCode}</span> : null}</div><p className="mt-1 flex items-center gap-1 truncate text-[#647579]"><MapPin size={12}/>{photo.location ?? 'Lokasi belum ada'}</p></div></Link>)}</div></section>) : <div className="rounded border border-[#d9e0dc] bg-white px-6 py-16 text-center"><CalendarDays size={38} className="mx-auto text-[#91a39d]"/><h2 className="mt-3 text-lg font-bold">Tidak ada foto pada tanggal ini</h2><p className="mt-2 text-sm text-[#647579]">Pilih tanggal lain atau hapus filter untuk melihat foto.</p><Link href="/timeline?date=all" className="mt-4 inline-block text-sm text-[#116a5c] underline">Lihat semua foto</Link></div>}
      {items.length < total && <div className="flex items-center justify-center gap-4 border-t border-[#d9e0dc] pt-5"><Link href={pageHref} className="rounded border border-[#b5c8c0] bg-white px-5 py-2 text-sm text-[#116a5c]">Muat lebih banyak <ChevronDown size={15} className="ml-1 inline"/></Link><span className="text-xs text-[#647579]">{items.length} dari {total} foto</span></div>}
    </div>
  </div>;
}
