import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, CheckCircle2, Download, ExternalLink, FilePenLine, ImageIcon, TriangleAlert } from 'lucide-react';
import { db } from '@/db';
import { assets, issuePagePhotos, issuePages, photos } from '@/db/schema';
import { and, asc, eq } from 'drizzle-orm';
import { publicationChecklist } from '@/lib/issue-publication';
import { cancelIssueScheduleAction, publishIssueAction, saveIssuePdfLayoutAction, scheduleIssueAction, unpublishIssueAction } from '../../actions';
import { jakartaScheduleDefaults } from '@/lib/issue-schedule';
import { getIssuePdfMargins } from '@/lib/issue-pdf-settings';

export default async function IssuePreviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ scheduleError?: string; scheduledAt?: string; pdfSaved?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const { earliest, suggested, currentLabel } = jakartaScheduleDefaults();
  const entered = query.scheduledAt && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(query.scheduledAt) ? query.scheduledAt : suggested;
  const check = publicationChecklist(id);
  const issue = check.issue;
  if (!issue) notFound();
  const margins = getIssuePdfMargins(id);
  const pages = db.select({ pageId: issuePages.id, pageNumber: issuePages.pageNumber, filename: photos.filename, caption: issuePagePhotos.caption, altText: issuePagePhotos.altText, assetId: assets.id }).from(issuePages).innerJoin(issuePagePhotos, eq(issuePagePhotos.pageId, issuePages.id)).innerJoin(photos, eq(photos.id, issuePagePhotos.photoId)).leftJoin(assets, and(eq(assets.photoId, photos.id), eq(assets.type, 'viewer'))).where(eq(issuePages.issueId, id)).orderBy(asc(issuePages.pageNumber)).all();
  return <div className="mx-auto max-w-5xl space-y-6 pb-10"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/issues" className="flex items-center gap-2 text-sm text-[#116a5c]"><ArrowLeft size={17}/>Kembali ke Issue</Link>{issue.status === 'Draft' && <Link href={`/issues/${id}/edit`} className="flex items-center gap-2 rounded border border-[#116a5c] px-4 py-2 text-sm text-[#116a5c]"><FilePenLine size={17}/>Edit Draft</Link>}</div>
    <header className="border-b border-[#d9dfdc] pb-5 text-center"><p className="font-mono text-xs tracking-widest text-[#116a5c]">{issue.code} · {issue.status.toUpperCase()}</p><h1 className="mt-2 text-4xl font-extrabold">{issue.title}</h1>{issue.subtitle && <p className="mt-2 text-lg text-[#647579]">{issue.subtitle}</p>}{issue.description && <p className="mx-auto mt-4 max-w-2xl whitespace-pre-wrap text-sm text-[#647579]">{issue.description}</p>}</header>
    <section className="rounded border border-[#d9dfdc] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Final Issue</h2><p className="text-sm text-[#657579]">{pages.length} halaman · Visibilitas {issue.visibility}</p></div>{issue.status === 'Published' && <Link href={`/issues/${issue.slug}`} target="_blank" className="flex items-center gap-2 rounded bg-[#116a5c] px-4 py-2 text-sm text-white">Buka Halaman Publik <ExternalLink size={15}/></Link>}</div>
      {check.errors.length ? <div className="mt-4 rounded bg-[#fff3df] p-4 text-sm text-[#81571c]"><p className="flex items-center gap-2 font-semibold"><TriangleAlert size={18}/>Perlu dilengkapi sebelum terbit</p><ul className="mt-2 list-disc space-y-1 pl-5">{check.errors.map(error => <li key={error}>{error}</li>)}</ul></div> : <p className="mt-4 flex items-center gap-2 rounded bg-[#e8f3eb] p-4 text-sm text-[#116a5c]"><CheckCircle2 size={18}/>Judul, sampul, halaman, gambar, dan alt text siap.</p>}
      {['Draft', 'Unpublished'].includes(issue.status) && <form action={publishIssueAction.bind(null, id)} className="mt-4"><button disabled={check.errors.length > 0} className="rounded bg-[#116a5c] px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Terbitkan Final Issue</button><p className="mt-2 text-xs text-[#657579]">Setelah terbit, halaman dan gambar viewer dapat diakses publik melalui URL Issue.</p></form>}
      {['Draft', 'Unpublished'].includes(issue.status) && <form action={scheduleIssueAction.bind(null, id)} className="mt-5 border-t border-[#d9dfdc] pt-5"><label htmlFor="scheduledAt" className="block text-sm font-semibold">Jadwalkan terbit</label><p className="mt-1 text-xs text-[#657579]">Waktu Indonesia Barat (WIB). Issue akan diterbitkan otomatis saat aplikasi berjalan.</p>{query.scheduleError && <p role="alert" className="mt-3 rounded bg-[#fff3df] p-3 text-sm text-[#81571c]">Pilih tanggal dan jam WIB setelah waktu sekarang. Saat ini {currentLabel} WIB.</p>}<div className="mt-3 flex flex-wrap gap-2"><input id="scheduledAt" name="scheduledAt" type="datetime-local" required min={earliest} defaultValue={entered} aria-invalid={Boolean(query.scheduleError)} className="rounded border border-[#cbd4d1] px-3 py-2 text-sm"/><button disabled={check.errors.length > 0} className="rounded border border-[#116a5c] px-4 py-2 text-sm font-semibold text-[#116a5c] disabled:cursor-not-allowed disabled:opacity-40">Simpan Jadwal</button></div></form>}
      {issue.status === 'Scheduled' && <div className="mt-5 rounded bg-[#e8f3eb] p-4 text-sm"><p className="font-semibold text-[#116a5c]">Dijadwalkan terbit {issue.scheduledAt?.toLocaleString('id-ID', { timeZone: 'Asia/Jakarta', dateStyle: 'full', timeStyle: 'short' })} WIB</p><form action={cancelIssueScheduleAction.bind(null, id)} className="mt-3"><button className="rounded border border-[#116a5c] bg-white px-4 py-2 text-[#116a5c]">Batalkan jadwal dan kembali ke draft</button></form></div>}
      {pages.length > 0 && <a href={`/api/issues/${id}/pdf`} className="mt-5 inline-flex items-center gap-2 rounded border border-[#116a5c] px-4 py-2 text-sm text-[#116a5c]"><Download size={16}/>Ekspor PDF</a>}
      {issue.status === 'Published' && <details className="mt-4 rounded border border-[#e3d3cf] p-3 text-sm"><summary className="cursor-pointer text-[#a13b2b]">Batalkan publikasi</summary><p className="mt-2 text-[#657579]">Halaman publik akan langsung ditutup. Draft dan foto tetap tersimpan.</p><form action={unpublishIssueAction.bind(null, id)}><button className="mt-3 rounded border border-[#a13b2b] px-4 py-2 text-[#a13b2b]">Ya, batalkan publikasi</button></form></details>}
    </section>
    {pages.length ? <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 rounded border border-[#d9dfdc] bg-white p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 px-1"><div><h2 className="font-bold">Pratinjau PDF</h2><p className="text-xs text-[#657579]">A4 · {pages.length} halaman · tampilan sama dengan file ekspor</p></div><a href={`/api/issues/${id}/pdf`} className="inline-flex items-center gap-2 text-sm text-[#116a5c]"><Download size={15}/>Unduh PDF</a></div><iframe title={`Pratinjau PDF ${issue.title}`} src={`/api/issues/${id}/pdf?view=1${query.pdfSaved ? `&updated=${encodeURIComponent(query.pdfSaved)}` : ''}`} className="h-[min(78vh,900px)] min-h-[540px] w-full rounded bg-[#e8ece9]"/></div><form action={saveIssuePdfLayoutAction.bind(null, id)} className="self-start rounded border border-[#d9dfdc] bg-white p-4"><h2 className="font-bold">Tata letak PDF</h2><p className="mt-1 text-xs text-[#657579]">Atur margin dalam milimeter dan caption per halaman, lalu simpan untuk memperbarui pratinjau.</p><div className="mt-4 grid grid-cols-2 gap-3">{(['top', 'right', 'bottom', 'left'] as const).map(side => <label key={side} className="text-xs font-medium capitalize text-[#405153]">{({ top: 'Atas', right: 'Kanan', bottom: 'Bawah', left: 'Kiri' })[side]} (mm)<input name={`margin-${side}`} type="number" min="5" max="50" step="0.1" required defaultValue={margins[side]} className="mt-1 w-full rounded border border-[#cbd4d1] px-3 py-2 text-sm text-[#192326]"/></label>)}</div><div className="mt-5 space-y-4 border-t border-[#d9dfdc] pt-4"><h3 className="text-sm font-semibold">Caption halaman</h3>{pages.map(page => <label key={page.pageId} className="block text-xs font-medium text-[#405153]"><span className="mb-1 block">{String(page.pageNumber).padStart(2, '0')} · {page.filename}</span><textarea name={`caption-${page.pageId}`} maxLength={500} rows={3} defaultValue={page.caption || ''} placeholder={page.filename} className="w-full rounded border border-[#cbd4d1] px-3 py-2 text-sm text-[#192326]"/></label>)}</div><button className="mt-5 w-full rounded bg-[#116a5c] px-4 py-2.5 text-sm font-semibold text-white">Simpan Tata Letak</button>{query.pdfSaved && <p role="status" className="mt-2 text-center text-xs text-[#116a5c]">Tata letak PDF tersimpan.</p>}</form></section> : <div className="rounded border border-[#d9dfdc] bg-white py-16 text-center"><ImageIcon size={38} className="mx-auto text-[#91a49d]"/><p className="mt-3 text-sm text-[#647579]">Belum ada foto dalam Issue ini.</p><Link href={`/issues/${id}/edit`} className="mt-3 inline-block text-sm text-[#116a5c] underline">Tambahkan foto</Link></div>}
  </div>;
}
