import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { and, asc, eq } from 'drizzle-orm';
import { AlertTriangle, ArrowLeft, CheckCircle2, Download, ExternalLink, Globe2, ImageIcon, LockKeyhole, Save } from 'lucide-react';
import { db } from '@/db';
import { assets, issuePagePhotos, issuePages, photos } from '@/db/schema';
import { IssuePdfViewer } from '@/components/IssuePdfViewer';
import { publicationChecklist } from '@/lib/issue-publication';
import { jakartaScheduleDefaults } from '@/lib/issue-schedule';
import { getIssuePdfMargins } from '@/lib/issue-pdf-settings';
import { cancelIssueScheduleAction, publishIssueAction, saveIssuePdfLayoutAction, scheduleIssueAction, unpublishIssueAction } from '../../actions';

export default async function IssuePreviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ scheduleError?: string; scheduledAt?: string; pdfSaved?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const check = publicationChecklist(id);
  const issue = check.issue;
  if (!issue) notFound();
  const margins = getIssuePdfMargins(id);
  const { earliest, suggested, currentLabel } = jakartaScheduleDefaults();
  const entered = query.scheduledAt && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(query.scheduledAt) ? query.scheduledAt : suggested;
  const pages = db.select({ pageId: issuePages.id, pageNumber: issuePages.pageNumber, filename: photos.filename, caption: issuePagePhotos.caption, altText: issuePagePhotos.altText, assetId: assets.id }).from(issuePages).innerJoin(issuePagePhotos, eq(issuePagePhotos.pageId, issuePages.id)).innerJoin(photos, eq(photos.id, issuePagePhotos.photoId)).leftJoin(assets, and(eq(assets.photoId, photos.id), eq(assets.type, 'viewer'))).where(eq(issuePages.issueId, id)).orderBy(asc(issuePages.pageNumber)).all();
  const missingAlt = pages.filter(page => !page.altText?.trim()).length;
  const canPublish = ['Draft', 'Unpublished'].includes(issue.status) && check.errors.length === 0;

  return <div className="-mx-7 -mb-5 bg-[#fdfdfb] max-sm:-mx-4"><div className="grid min-h-[calc(100dvh-88px)] xl:grid-cols-[minmax(0,1fr)_350px]">
    <main className="min-w-0 px-5 pb-6 pt-4 lg:px-7"><div className="flex items-center gap-2 text-xs text-[#5d6d70]"><Link href={`/issues/${id}/edit`} className="hover:text-[#076b5c]">Issue Builder</Link><span>/</span><strong className="text-[#172329]">Preview &amp; Publish</strong></div><div className="mt-2 flex flex-wrap items-end justify-between gap-2"><div><h1 className="font-serif text-[clamp(28px,2.5vw,40px)] font-bold leading-tight">Preview &amp; Publish Issue</h1><p className="text-sm text-[#65747a]">Tinjau hasil akhir issue sebelum dipublikasikan.</p></div><a href={`/api/issues/${id}/pdf`} className="flex items-center gap-2 rounded border border-[#cdd8d1] bg-white px-3 py-2 text-xs font-semibold text-[#0b6254]"><Download size={15}/>Ekspor PDF</a></div><div className="mt-5 flex flex-wrap items-center gap-3"><h2 className="font-serif text-[clamp(22px,2vw,31px)] font-bold">{issue.title}</h2><span className="rounded bg-[#e3f3e9] px-2 py-1 text-xs text-[#0b6254]">{issue.status === 'Draft' ? 'Draft tersimpan' : issue.status}</span></div>
      {pages.length ? <IssuePdfViewer issueId={id} title={issue.title} pages={pages.map(page => ({ pageNumber: page.pageNumber, assetId: page.assetId, filename: page.filename }))} revision={query.pdfSaved}/> : <div className="mt-6 rounded border border-[#d9dfdc] bg-white py-16 text-center"><ImageIcon size={38} className="mx-auto text-[#91a49d]"/><p className="mt-3 text-sm text-[#647579]">Belum ada foto dalam Issue ini.</p><Link href={`/issues/${id}/edit`} className="mt-3 inline-block text-sm text-[#116a5c] underline">Tambahkan foto</Link></div>}
    </main>

    <aside className="border-t border-[#d9dfdc] bg-white px-5 py-5 xl:border-l xl:border-t-0"><h2 className="font-serif text-lg font-bold">Langkah Publikasi</h2><ol className="mt-4 space-y-4 text-sm"><li className="flex gap-3"><CheckCircle2 className="shrink-0 text-[#076b5c]" size={23}/><span><strong>1. Detail Issue</strong><small className="block text-[#65747a]">Judul, deskripsi, dan informasi dasar</small></span></li><li className="flex gap-3"><CheckCircle2 className="shrink-0 text-[#076b5c]" size={23}/><span><strong>2. Susunan Halaman</strong><small className="block text-[#65747a]">{pages.length} halaman telah disusun</small></span></li><li className="flex gap-3">{check.errors.length ? <AlertTriangle className="shrink-0 text-[#b87525]" size={23}/> : <CheckCircle2 className="shrink-0 text-[#076b5c]" size={23}/>}<span><strong>3. Pemeriksaan</strong><small className={check.errors.length ? 'block text-[#a56d22]' : 'block text-[#65747a]'}>{check.errors.length ? `${check.errors.length} catatan` : 'Semua pemeriksaan lolos'}</small></span></li><li className="flex gap-3"><Globe2 className="shrink-0 text-[#076b5c]" size={23}/><span><strong>4. Publikasi</strong><small className="block text-[#65747a]">Atur waktu terbit</small></span></li></ol>
      <div className="mt-5 border-t border-[#d9dfdc] pt-4"><h3 className="font-serif text-base font-bold">Pengaturan Publikasi</h3><label className="mt-3 block text-xs font-semibold">Slug URL<input readOnly value={`/issues/${issue.slug}`} className="mt-1 w-full rounded border border-[#cbd4d1] bg-[#fbfcfb] px-3 py-2 text-sm font-normal"/></label><p className="mt-4 text-xs font-semibold">Visibilitas</p><div className="mt-1 flex rounded border border-[#cbd4d1] text-xs"><span className={`flex flex-1 items-center justify-center gap-1 rounded py-2 ${issue.visibility === 'Public' || canPublish ? 'bg-[#e6f3ed] text-[#075f52]' : ''}`}><Globe2 size={14}/>Publik</span><span className={`flex flex-1 items-center justify-center gap-1 border-l border-[#cbd4d1] py-2 ${issue.visibility === 'Private' && !canPublish ? 'bg-[#eef1ef]' : ''}`}><LockKeyhole size={14}/>Privat</span></div><p className="mt-2 text-[11px] text-[#65747a]">Publikasi membuat halaman Issue dapat diakses melalui URL di atas.</p>
      {['Draft', 'Unpublished'].includes(issue.status) && <div className="mt-5"><h4 className="text-xs font-semibold">Waktu Publikasi</h4><p className="mt-2 text-xs">● Terbitkan sekarang</p><details className="mt-2 rounded border border-[#d8e0dc] p-3"><summary className="cursor-pointer text-xs font-semibold text-[#116a5c]">Jadwalkan terbit</summary><form action={scheduleIssueAction.bind(null, id)} className="mt-3"><p className="text-xs text-[#65747a]">Waktu Indonesia Barat (WIB). Issue terbit otomatis saat aplikasi berjalan.</p>{query.scheduleError && <p role="alert" className="mt-2 rounded bg-[#fff3df] p-2 text-xs text-[#81571c]">Pilih waktu setelah {currentLabel} WIB.</p>}<input name="scheduledAt" type="datetime-local" required min={earliest} defaultValue={entered} aria-label="Waktu terbit WIB" className="mt-2 w-full rounded border border-[#cbd4d1] px-2 py-2 text-xs"/><button disabled={!canPublish} className="mt-2 w-full rounded border border-[#116a5c] px-3 py-2 text-xs font-semibold text-[#116a5c] disabled:opacity-40">Simpan Jadwal</button></form></details></div>}
      {issue.status === 'Scheduled' && <div className="mt-4 rounded bg-[#e8f3eb] p-3 text-xs"><p className="font-semibold text-[#116a5c]">Terbit {issue.scheduledAt?.toLocaleString('id-ID', { timeZone: 'Asia/Jakarta', dateStyle: 'full', timeStyle: 'short' })} WIB</p><form action={cancelIssueScheduleAction.bind(null, id)} className="mt-2"><button className="underline">Batalkan jadwal</button></form></div>}
      <div className="mt-5"><h4 className="text-xs font-semibold">Kover Issue</h4><div className="mt-2 flex items-center gap-3"><div className="relative h-22 w-16 overflow-hidden rounded bg-[#e7ece9]">{pages[0]?.assetId ? <Image src={`/api/assets/${pages[0].assetId}`} alt="Sampul Issue" fill unoptimized sizes="64px" className="object-cover grayscale"/> : null}</div><Link href={`/issues/${id}/edit`} className="rounded border border-[#cbd4d1] px-3 py-2 text-xs">Ganti Sampul</Link></div></div>
      </div>
      <form id="issue-pdf-layout" action={saveIssuePdfLayoutAction.bind(null, id)} className="mt-5 border-t border-[#d9dfdc] pt-4"><h3 className="font-serif text-base font-bold">Tata Letak PDF</h3><p className="mt-1 text-xs text-[#65747a]">Margin dan caption diterapkan langsung pada PDF.</p><div className="mt-3 grid grid-cols-2 gap-2">{(['top', 'right', 'bottom', 'left'] as const).map(side => <label key={side} className="text-xs">Margin {({ top: 'atas', right: 'kanan', bottom: 'bawah', left: 'kiri' })[side]} (mm)<input name={`margin-${side}`} type="number" min="5" max="50" step="0.1" required defaultValue={margins[side]} className="mt-1 w-full rounded border border-[#cbd4d1] px-2 py-2 text-xs"/></label>)}</div><details className="mt-4"><summary className="cursor-pointer text-xs font-semibold">Caption halaman ({pages.length})</summary><div className="mt-2 max-h-60 space-y-3 overflow-y-auto">{pages.map(page => <label key={page.pageId} className="block text-xs"><span>{String(page.pageNumber).padStart(2, '0')} · {page.filename}</span><textarea name={`caption-${page.pageId}`} maxLength={500} rows={2} defaultValue={page.caption || ''} className="mt-1 w-full rounded border border-[#cbd4d1] px-2 py-2 text-xs"/></label>)}</div></details><button className="mt-4 w-full rounded border border-[#116a5c] px-3 py-2 text-xs font-semibold text-[#116a5c]">Simpan Tata Letak</button>{query.pdfSaved && <p role="status" className="mt-2 text-xs text-[#116a5c]">Tata letak PDF tersimpan.</p>}</form>
      {issue.status === 'Published' && <div className="mt-5 space-y-2 border-t border-[#d9dfdc] pt-4"><Link href={`/issues/${issue.slug}`} target="_blank" className="flex items-center gap-2 text-xs text-[#116a5c]">Buka halaman publik <ExternalLink size={13}/></Link><details className="text-xs text-[#a13b2b]"><summary className="cursor-pointer">Batalkan publikasi</summary><form action={unpublishIssueAction.bind(null, id)}><button className="mt-2 rounded border border-[#a13b2b] px-3 py-2">Ya, batalkan publikasi</button></form></details></div>}
      {check.errors.length > 0 && <div className="mt-5 rounded border border-[#ecd9ba] bg-[#fff8ed] p-3 text-xs text-[#865b1e]"><strong>Perlu dilengkapi sebelum terbit</strong><ul className="mt-2 list-disc space-y-1 pl-4">{check.errors.map(error => <li key={error}>{error}</li>)}</ul></div>}
    </aside>
  </div>
  <div className="sticky bottom-0 z-20 flex flex-wrap items-center gap-2 border-t border-[#d9dfdc] bg-white px-5 py-3 shadow-[0_-5px_20px_#1723290a]"><Link href={`/issues/${id}/edit`} className="flex items-center gap-2 rounded border border-[#9facaa] px-4 py-2 text-xs"><ArrowLeft size={16}/>Kembali ke Builder</Link><button form="issue-pdf-layout" className="flex items-center gap-2 rounded border border-[#9facaa] px-4 py-2 text-xs"><Save size={16}/>Simpan Draft</button><div className={`ml-auto flex items-center gap-2 rounded px-3 py-2 text-xs ${check.errors.length ? 'bg-[#fff4e6] text-[#8c5d1b]' : 'bg-[#e8f4ed] text-[#0c654f]'}`}>{check.errors.length ? <AlertTriangle size={17}/> : <CheckCircle2 size={17}/>}<span>{check.errors.length ? `${check.errors.length} hal perlu diperiksa` : 'Siap dipublikasikan'}{missingAlt > 0 && ` · ${missingAlt} foto belum memiliki alt text`}</span></div>{canPublish && <form action={publishIssueAction.bind(null, id)}><button className="flex items-center gap-2 rounded bg-[#076b5c] px-5 py-2.5 text-sm font-semibold text-white"><Globe2 size={17}/>Publikasikan Issue</button></form>}{issue.status === 'Published' && <span className="flex items-center gap-2 rounded bg-[#dff1eb] px-4 py-2 text-sm text-[#075f52]"><CheckCircle2 size={17}/>Issue sudah terbit</span>}{issue.status === 'Scheduled' && <span className="rounded bg-[#dff1eb] px-4 py-2 text-sm text-[#075f52]">Issue dijadwalkan</span>}</div>
  </div>;
}
