import Link from 'next/link';
import { BookOpen, CalendarDays, Database, FolderUp, HeartPulse, ImageIcon, Plus, ShieldCheck, ArrowRight } from 'lucide-react';
import { db } from '@/db';
import { assets, backups, importItems, importSessions, issues, livePhotos, photos } from '@/db/schema';
import { and, count, desc, eq, isNull, sql } from 'drizzle-orm';
import { getAppPreferences } from '@/lib/app-preferences';

const card = 'rounded-md border border-[#d9dfdc] bg-white';
const monthName = new Intl.DateTimeFormat('id-ID', { month: 'short' });
export default function DashboardPage() {
  const active = isNull(photos.deletedAt);
  const photoCount = db.select({ value: count() }).from(photos).where(active).get()?.value ?? 0;
  const issueCount = db.select({ value: count() }).from(issues).get()?.value ?? 0;
  const liveCount = db.select({ value: count() }).from(livePhotos).innerJoin(photos, eq(livePhotos.photoId, photos.id)).where(active).get()?.value ?? 0;
  const bytes = db.select({ value: sql<number>`coalesce(sum(${assets.bytes}), 0)` }).from(assets).get()?.value ?? 0;
  const range = db.select({ first: sql<number | null>`min(${photos.capturedAt})`, last: sql<number | null>`max(${photos.capturedAt})` }).from(photos).where(active).get();
  const recent = db.select({ id: photos.id, filename: photos.filename, capturedAt: photos.capturedAt, status: photos.status, thumbnailId: assets.id, importedAt: importSessions.startedAt })
    .from(photos)
    .leftJoin(assets, and(eq(assets.photoId, photos.id), eq(assets.type, 'thumbnail')))
    .leftJoin(importItems, and(eq(importItems.photoId, photos.id), eq(importItems.status, 'Imported')))
    .leftJoin(importSessions, eq(importSessions.id, importItems.sessionId))
    .where(active)
    .orderBy(desc(importSessions.startedAt), desc(sql`import_items.rowid`), desc(photos.capturedAt))
    .limit(6).all();
  const latestBackup = db.select().from(backups).orderBy(desc(backups.createdAt)).limit(1).get();
  const today = new Date();
  const months = Array.from({ length: 6 }, (_, i) => { const date = new Date(today.getFullYear(), today.getMonth() - 5 + i, 1); return { key: `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`, label: monthName.format(date) }; });
  const grouped = db.select({ month: sql<string>`strftime('%Y-%m', ${photos.capturedAt}, 'unixepoch')`, value: count() }).from(photos).where(and(active, sql`${photos.capturedAt} >= ${Math.floor(new Date(today.getFullYear(), today.getMonth() - 5, 1).getTime() / 1000)}`)).groupBy(sql`strftime('%Y-%m', ${photos.capturedAt}, 'unixepoch')`).all();
  const counts = months.map(month => ({ ...month, value: grouped.find(row => row.month === month.key)?.value ?? 0 }));
  const highest = Math.max(1, ...counts.map(item => item.value));
  const rangeLabel = range?.first && range.last ? `${new Date(range.first * 1000).getFullYear()}–${new Date(range.last * 1000).getFullYear()}` : '—';
  const stats = getAppPreferences().showStats ? [{ label: 'Total Foto', value: photoCount.toLocaleString('id-ID'), icon: ImageIcon }, { label: 'Issue', value: issueCount.toLocaleString('id-ID'), icon: BookOpen }, { label: 'LIVE', value: liveCount.toLocaleString('id-ID'), icon: HeartPulse }, { label: 'Rentang Arsip', value: rangeLabel, icon: CalendarDays }] : [];

  return <div className="mx-auto max-w-[1500px] space-y-4 pb-5">
    <div className="flex flex-wrap items-end justify-between gap-4 pb-3"><div><h1 className="text-[clamp(28px,2.3vw,38px)] font-extrabold tracking-tight leading-tight">Selamat datang di ChronoVista.</h1><p className="text-[17px] tracking-wide text-[#68737b]">Arsip Anda terus bertumbuh.</p></div></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-[repeat(4,minmax(0,1fr))_minmax(190px,.9fr)]">{stats.map(item => <div key={item.label} className={`${card} flex min-h-27 items-center gap-4 px-5`}><item.icon className="h-9 w-9 shrink-0 text-[#175b56] stroke-[1.5]"/><div><strong className="block text-[clamp(20px,1.9vw,31px)] leading-none tracking-tight">{item.value}</strong><span className="mt-2 block text-sm text-[#53626c]">{item.label}</span></div></div>)}<div className="col-span-2 grid gap-2 sm:grid-cols-2 xl:col-span-1 xl:grid-cols-1"><Link href="/import" className="flex items-center justify-center gap-2 rounded bg-[#116a5c] px-4 py-3 text-white hover:bg-[#0b554b]"><Plus size={19}/>Import Foto</Link><Link href="/issues/new" className="flex items-center justify-center gap-2 rounded border border-[#116a5c] bg-white px-4 py-3 text-[#153f3a] hover:bg-[#ecf4f0]"><BookOpen size={19}/>Buat Issue</Link></div></div>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1.55fr)_minmax(0,1.12fr)_minmax(250px,.92fr)]">
      <section className={`${card} min-h-76 p-5`}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Pertumbuhan Arsip</h2><span className="rounded border px-3 py-1 text-xs">6 Bulan</span></div><div className="mt-5 flex h-51 items-end gap-3 border-b border-[#bfc9c7] px-2">{counts.map(item => <div key={item.key} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><span className="text-xs text-[#53626c]">{item.value || ''}</span><div className="w-full max-w-12 rounded-t bg-[#187060]" style={{ height: `${Math.max(item.value ? 5 : 1, item.value / highest * 78)}%` }}/><span className="relative -bottom-6 text-xs text-[#68737b]">{item.label}</span></div>)}</div>{photoCount === 0 && <p className="mt-7 text-center text-sm text-[#68737b]">Grafik akan terisi setelah foto diimpor.</p>}</section>
      <section className={`${card} min-h-76 p-5`}><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-bold">Aktivitas Terbaru</h2><Link href="/archive" className="flex items-center gap-1 text-sm text-[#126659]">Lihat semua <ArrowRight size={15}/></Link></div>{recent.length ? <div className="mt-3 divide-y">{recent.slice(0,4).map(photo => <Link key={photo.id} href={`/photos/${photo.id}`} className="flex items-center gap-3 py-2.5"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded bg-[#e9efec] text-[#52736d]">{photo.thumbnailId ? <img src={`/api/assets/${photo.thumbnailId}`} alt="" className="h-full w-full object-cover"/> : <ImageIcon size={22}/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{photo.filename}</p><p className="text-xs text-[#68737b]">{photo.capturedAt ? photo.capturedAt.toLocaleDateString('id-ID') : photo.importedAt ? `Diimpor ${photo.importedAt.toLocaleDateString('id-ID')}` : 'Tanggal belum ada'}</p></div><span className="rounded bg-[#e4f2eb] px-2 py-1 text-xs text-[#27695f]">{photo.status}</span></Link>)}</div> : <p className="mt-14 text-center text-sm text-[#68737b]">Aktivitas foto akan muncul setelah import pertama.</p>}</section>
      <section className={`${card} p-5`}><h2 className="text-lg font-bold">Aksi Cepat</h2><div className="mt-4 grid grid-cols-2 gap-3">{[{ icon: FolderUp, label: 'Import Folder', href: '/import' }, { icon: BookOpen, label: 'Buat Issue', href: '/issues/new' }, { icon: ShieldCheck, label: 'Periksa Arsip', href: '/archive?status=Need+Review' }, { icon: Database, label: 'Backup Database', href: '/settings/backup' }].map(action => <Link key={action.label} href={action.href} className="flex min-h-25 flex-col items-center justify-center gap-2 rounded border border-[#d9dfdc] text-center text-sm hover:bg-[#edf5f1]"><action.icon size={27} strokeWidth={1.5}/>{action.label}</Link>)}</div></section>
    </div>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,2.73fr)_minmax(250px,.92fr)]"><section className={`${card} min-h-62 p-5`}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Foto Terbaru</h2><Link href="/archive" className="flex items-center gap-1 text-sm text-[#126659]">Lihat semua <ArrowRight size={15}/></Link></div>{recent.length ? <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{recent.map(photo => <Link key={photo.id} href={`/photos/${photo.id}`} className="min-w-0"><div className="flex aspect-[1.15] items-center justify-center overflow-hidden rounded bg-[#e8eeeb] text-[#78918a]">{photo.thumbnailId ? <img src={`/api/assets/${photo.thumbnailId}`} alt="" loading="lazy" className="h-full w-full object-cover"/> : <ImageIcon size={32}/>}</div><p className="mt-2 truncate text-xs text-[#68737b]">{photo.capturedAt ? photo.capturedAt.toLocaleDateString('id-ID') : photo.importedAt ? `Diimpor ${photo.importedAt.toLocaleDateString('id-ID')}` : 'Tanggal belum ada'}</p><p className="truncate text-xs font-medium">{photo.filename}</p></Link>)}</div> : <div className="flex min-h-43 flex-col items-center justify-center text-center text-[#68737b]"><ImageIcon size={30}/><p className="mt-2 text-sm">Belum ada foto di arsip.</p><Link href="/import" className="mt-2 text-sm text-[#126659] underline">Import foto pertama</Link></div>}</section><div className="space-y-3"><section className={`${card} p-5`}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">SQLite Lokal</h2><span className="flex items-center gap-1.5 text-xs text-[#168266]"><span className="h-2.5 w-2.5 rounded-full bg-[#25a57e]"/>Aktif</span></div><p className="mt-4 text-xs text-[#68737b]">Backup terakhir</p><p className="text-sm">{latestBackup ? latestBackup.createdAt.toLocaleString('id-ID') : 'Belum ada backup'}</p><p className="mt-4 text-xs text-[#68737b]">Media tersimpan</p><p className="text-sm font-medium">{(bytes / 1024 / 1024).toLocaleString('id-ID', { maximumFractionDigits: 1 })} MB</p><div className="mt-2 h-2 rounded-full bg-[#e0e6e3]"><div className="h-full min-w-1 rounded-full bg-[#14715e]" style={{ width: `${Math.min(100, Math.max(1, bytes / (50 * 1024 ** 3) * 100))}%` }}/></div></section><blockquote className="px-4 py-2 text-sm italic leading-relaxed text-[#68737b]">“Foto bukan sekadar kenangan, tapi cara kita melihat kembali siapa kita.”<span className="mt-2 block not-italic">— ChronoVista</span></blockquote></div></div>
  </div>;
}
