import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Aperture, ArrowLeft } from 'lucide-react';
import { db } from '@/db';
import { assets, issuePagePhotos, issuePages, issues, photos, users } from '@/db/schema';
import { and, asc, eq, isNull } from 'drizzle-orm';

export default async function PublicIssuePage({ params }: { params: Promise<{ id: string }> }) {
  const { id: slug } = await params;
  const issue = db.select().from(issues).where(and(eq(issues.slug, slug), eq(issues.status, 'Published'), eq(issues.visibility, 'Public'))).get();
  if (!issue) notFound();
  const pages = db.select({ pageNumber: issuePages.pageNumber, caption: issuePagePhotos.caption, altText: issuePagePhotos.altText, assetId: assets.id }).from(issuePages).innerJoin(issuePagePhotos, eq(issuePagePhotos.pageId, issuePages.id)).innerJoin(photos, eq(photos.id, issuePagePhotos.photoId)).innerJoin(assets, and(eq(assets.photoId, photos.id), eq(assets.type, 'viewer'))).where(and(eq(issuePages.issueId, issue.id), isNull(photos.deletedAt))).orderBy(asc(issuePages.pageNumber)).all();
  const author = db.select({ displayName: users.displayName, username: users.username }).from(users).limit(1).get();
  return <main className="min-h-screen bg-[#f7f6f1] text-[#192326]"><header className="mx-auto flex max-w-6xl items-center justify-between border-b border-[#d7deda] px-5 py-5"><Link href="/" className="flex items-center gap-2 text-lg font-bold"><Aperture size={27}/>ChronoVista</Link><Link href="/" className="flex items-center gap-2 text-sm text-[#116a5c]"><ArrowLeft size={16}/>Beranda</Link></header><div className="mx-auto max-w-4xl px-5 pb-18"><div className="py-14 text-center"><p className="font-mono text-xs font-semibold tracking-[.25em] text-[#116a5c]">{issue.code} · FINAL ISSUE</p><h1 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight sm:text-6xl">{issue.title}</h1>{issue.subtitle && <p className="mt-4 text-lg text-[#68777a]">{issue.subtitle}</p>}<p className="mt-5 text-sm text-[#657579]">{author?.displayName || author?.username || 'ChronoVista'}{issue.publishedAt && ` · ${issue.publishedAt.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}`}</p>{issue.description && <p className="mx-auto mt-6 max-w-2xl whitespace-pre-wrap text-sm leading-7 text-[#4d5e61]">{issue.description}</p>}</div><div className="space-y-16">{pages.map(page => <figure key={page.pageNumber}><div className="flex min-h-70 items-center justify-center bg-[#202525]">{page.assetId && <img src={`/api/public-assets/${page.assetId}`} alt={page.altText || ''} className="max-h-[85vh] max-w-full object-contain"/>}</div><figcaption className="mt-3 flex items-start justify-between gap-4 text-sm"><span>{page.caption || ''}</span><span className="font-mono text-xs text-[#788884]">{String(page.pageNumber).padStart(2, '0')}</span></figcaption></figure>)}</div><footer className="mt-18 border-t border-[#d7deda] pt-5 text-center font-mono text-xs tracking-widest text-[#71817d]">CHRONOVISTA · SETIAP FOTO PUNYA CERITA</footer></div></main>;
}
