'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Camera, Check, ChevronDown, Folder, Grid2X2, ImageIcon, List, LockKeyhole, MapPin, Plus, Search, SlidersHorizontal, X } from 'lucide-react';

export type ArchivePhoto = {
  id: string; filename: string; capturedAt: string | null; status: string; visibility: string;
  thumbnailUrl: string | null; location: string | null; latitude: number | null; longitude: number | null;
  camera: string | null; lens: string | null; iso: number | null; aperture: string | null; shutter: string | null; focal: string | null; inIssue: boolean;
};
type Filters = { q: string; status: string; year: string; camera: string; location: string; sort: string; view: string; page: number };

function dateLabel(value: string | null) { return value ? new Date(value).toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta', day: 'numeric', month: 'short', year: 'numeric' }) : 'Tanggal belum ada'; }
function timeLabel(value: string | null) { return value ? new Date(value).toLocaleTimeString('id-ID', { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit' }) : ''; }

export function ArchiveWorkspace({ items, total, stats, years, filters, defaultGridSize = 'medium' }: { items: ArchivePhoto[]; total: number; stats: { total: number; review: number; privateCount: number; noIssue: number }; years: { year: string; count: number }[]; filters: Filters; defaultGridSize?: 'small' | 'medium' | 'large' }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [activeId, setActiveId] = useState(items[0]?.id ?? '');
  const [summaryOpen, setSummaryOpen] = useState(true);
  const active = items.find(item => item.id === activeId) ?? items[0];
  const allSelected = items.length > 0 && items.every(item => selected.includes(item.id));
  const gridColumns = defaultGridSize === 'small' ? 'grid-cols-2 md:grid-cols-4 2xl:grid-cols-6' : defaultGridSize === 'large' ? 'grid-cols-1 md:grid-cols-2 2xl:grid-cols-3' : 'grid-cols-2 md:grid-cols-3 2xl:grid-cols-5';
  const link = (changes: Record<string, string>) => `/archive?${new URLSearchParams({ ...(filters.q ? { q: filters.q } : {}), ...(filters.status ? { status: filters.status } : {}), ...(filters.year ? { year: filters.year } : {}), ...(filters.camera ? { camera: filters.camera } : {}), ...(filters.location ? { location: filters.location } : {}), ...(filters.sort !== 'newest' ? { sort: filters.sort } : {}), ...(filters.view !== 'grid' ? { view: filters.view } : {}), ...changes })}`;
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const side = [{ label: 'Semua Foto', value: '', icon: ImageIcon, count: stats.total }, { label: 'Private', value: 'private', icon: LockKeyhole, count: stats.privateCount }, { label: 'Tanpa Issue', value: 'no-issue', icon: Folder, count: stats.noIssue }, { label: 'Perlu Diperiksa', value: 'review', icon: SlidersHorizontal, count: stats.review }];

  return <div className="-mx-7 -mb-5 flex min-h-[calc(100dvh-88px)] flex-col bg-[#fdfdfb] max-sm:-mx-4">
    <div className="grid min-h-0 flex-1 grid-cols-1 xl:grid-cols-[210px_minmax(0,1fr)_265px]">
      <aside className="hidden border-r border-[#dbe0dc] bg-white px-3 py-5 xl:block"><div className="mb-3 flex items-center justify-between px-2 text-xs font-bold tracking-wider">ARSIP <ChevronDown size={15}/></div><nav className="space-y-1">{side.map(item => <Link key={item.label} href={link({ status: item.value, page: '1' })} className={`flex items-center gap-3 rounded px-3 py-2 text-sm ${filters.status === item.value ? 'bg-[#dfeee8] font-semibold text-[#0b6356]' : 'hover:bg-[#f3f7f5]'}`}><item.icon size={18}/><span className="flex-1">{item.label}</span><span className="text-xs text-[#5b696a]">{item.count.toLocaleString('id-ID')}</span></Link>)}</nav><div className="my-5 border-t border-[#e0e4e1]"/><h2 className="px-2 text-xs font-bold tracking-wider">TAHUN</h2><nav className="mt-2 space-y-1">{years.map(item => <Link key={item.year} href={link({ year: filters.year === item.year ? '' : item.year, page: '1' })} className={`flex items-center gap-2 rounded px-3 py-2 text-sm ${filters.year === item.year ? 'bg-[#dfeee8] font-semibold text-[#0b6356]' : 'hover:bg-[#f3f7f5]'}`}><ChevronDown size={14} className="-rotate-90"/>{item.year}<span className="ml-auto text-xs text-[#647476]">{item.count}</span></Link>)}</nav><p className="mt-16 px-2 text-xs italic leading-5 text-[#82908d]">“Foto bukan sekadar gambar, tapi cara kita mengingat.”</p></aside>

      <main className="min-w-0 px-4 py-4 lg:px-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-[32px] font-extrabold leading-none tracking-tight">Arsip Foto</h1><p className="mt-1 text-sm text-[#627077]">Kelola seluruh koleksi fotografi dalam satu tempat.</p><p className="mt-2 text-xs font-semibold">{stats.total.toLocaleString('id-ID')} foto <span className="px-1 text-[#87938f]">·</span> {stats.noIssue.toLocaleString('id-ID')} tanpa issue <span className="px-1 text-[#87938f]">·</span> {stats.review.toLocaleString('id-ID')} perlu diperiksa</p></div><Link href="/import" className="flex h-10 items-center gap-2 rounded bg-[#076b5c] px-4 text-sm font-semibold text-white"><Plus size={18}/>Import Foto</Link></div>

        <form action="/archive" className="mt-3 space-y-2"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#5b686d]" size={18}/><input type="search" name="q" defaultValue={filters.q} placeholder="Cari filename, lokasi, atau kamera..." aria-label="Cari foto" className="h-10 w-full rounded border border-[#cfd8d3] bg-white pl-10 pr-3 text-sm"/></div><div className="flex flex-wrap gap-2"><select name="status" aria-label="Status" defaultValue={filters.status} className="h-9 rounded border border-[#cfd8d3] bg-white px-2 text-xs"><option value="">Status: Semua</option><option value="ready">Siap</option><option value="review">Perlu Diperiksa</option><option value="private">Private</option><option value="no-issue">Tanpa Issue</option></select><select name="year" aria-label="Tahun" defaultValue={filters.year} className="h-9 rounded border border-[#cfd8d3] bg-white px-2 text-xs"><option value="">Tahun: Semua</option>{years.map(item => <option key={item.year} value={item.year}>{item.year}</option>)}</select><input name="camera" defaultValue={filters.camera} aria-label="Filter kamera" placeholder="Kamera" className="h-9 w-27 rounded border border-[#cfd8d3] bg-white px-2 text-xs"/><input name="location" defaultValue={filters.location} aria-label="Filter lokasi" placeholder="Lokasi" className="h-9 w-26 rounded border border-[#cfd8d3] bg-white px-2 text-xs"/><select name="sort" aria-label="Urutan" defaultValue={filters.sort} className="h-9 rounded border border-[#cfd8d3] bg-white px-2 text-xs"><option value="newest">Tanggal Terbaru</option><option value="oldest">Tanggal Terlama</option></select><input type="hidden" name="view" value={filters.view}/><button className="flex h-9 items-center gap-1 rounded border border-[#cfd8d3] bg-white px-3 text-xs"><SlidersHorizontal size={14}/>Terapkan</button><div className="ml-auto flex h-9 overflow-hidden rounded border border-[#cfd8d3] bg-white">{[{ value: 'grid', icon: Grid2X2 }, { value: 'compact', icon: ImageIcon }, { value: 'list', icon: List }].map(mode => <Link key={mode.value} href={link({ view: mode.value, page: '1' })} aria-label={`Tampilan ${mode.value}`} className={`flex w-9 items-center justify-center border-l border-[#e5e9e6] first:border-l-0 ${filters.view === mode.value ? 'bg-[#dceee8] text-[#076b5c]' : ''}`}><mode.icon size={15}/></Link>)}</div></div></form>

        {(filters.q || filters.status || filters.year || filters.camera || filters.location) && <div className="mt-2 flex items-center gap-2 text-xs"><span className="rounded bg-[#0f6b5a] px-2 py-1 text-white">Filter aktif</span><Link href="/archive" className="text-[#116a5c] underline">Hapus semua</Link></div>}
        <div className="mt-4 flex items-baseline gap-3 border-b border-[#e3e7e4] pb-2"><h2 className="text-sm font-bold uppercase tracking-wide">{filters.year ? `Tahun ${filters.year}` : 'Semua Foto'}</h2><span className="text-xs text-[#647476]">{total.toLocaleString('id-ID')} foto</span></div>

        {items.length ? <div className={`mt-2 grid gap-2 ${filters.view === 'list' ? 'grid-cols-1' : filters.view === 'compact' ? 'grid-cols-2 md:grid-cols-4 2xl:grid-cols-6' : gridColumns}`}>{items.map(item => <article key={item.id} className={`min-w-0 overflow-hidden rounded border bg-white ${selected.includes(item.id) ? 'border-[#0e7967] ring-1 ring-[#0e7967]' : active?.id === item.id ? 'border-[#88b8a9]' : 'border-[#e0e5e1]'} ${filters.view === 'list' ? 'flex h-25' : ''}`}><div className={`relative bg-[#e9eeeb] ${filters.view === 'list' ? 'h-full w-36 shrink-0' : 'aspect-[1.55]'}`}><button type="button" onClick={() => { setActiveId(item.id); setSummaryOpen(true); }} aria-label={`Ringkasan ${item.filename}`} className="absolute inset-0 z-10">{item.thumbnailUrl ? <Image src={item.thumbnailUrl} alt="" fill unoptimized sizes="220px" className="object-cover grayscale"/> : <span className="flex h-full items-center justify-center"><ImageIcon size={26}/></span>}</button><button type="button" onClick={() => toggle(item.id)} aria-label={`Pilih ${item.filename}`} aria-pressed={selected.includes(item.id)} className={`absolute left-2 top-2 z-20 flex h-5 w-5 items-center justify-center rounded border border-[#82938d] ${selected.includes(item.id) ? 'bg-[#076b5c] text-white' : 'bg-white'}`}>{selected.includes(item.id) && <Check size={13}/>}</button></div><div className="min-w-0 flex-1 px-2 py-1.5"><p className="truncate font-mono text-[11px] font-bold">{item.filename}</p><p className="mt-0.5 text-[11px] text-[#647176]">{dateLabel(item.capturedAt)} · {timeLabel(item.capturedAt)}</p><p className="mt-0.5 flex items-center gap-1 truncate text-[11px] text-[#647176]"><MapPin size={11} className="shrink-0"/>{item.location || 'Lokasi belum ada'}</p><div className="mt-1 flex items-center justify-between gap-1"><span className="truncate text-[10px] text-[#647176]">{item.camera || 'EXIF belum ada'}</span><span className={`shrink-0 rounded px-1.5 py-0.5 text-[10px] ${item.status === 'Need Review' ? 'bg-[#fff1d9] text-[#8d5b12]' : item.visibility === 'Private' ? 'bg-[#e8ecef] text-[#4d5b62]' : 'bg-[#dff1eb] text-[#075f52]'}`}>{item.status === 'Need Review' ? 'PERIKSA' : item.visibility === 'Private' ? 'Private' : item.inIssue ? 'Issue' : 'LIVE'}</span></div></div></article>)}</div> : <div className="rounded border border-[#dce2de] bg-white py-14 text-center"><ImageIcon size={36} className="mx-auto text-[#9aaba4]"/><h2 className="mt-3 font-bold">Belum ada foto yang cocok</h2><Link href="/archive" className="mt-2 inline-block text-sm text-[#116a5c] underline">Hapus filter</Link></div>}
      </main>

      {summaryOpen && active && <aside className="border-t border-[#dbe0dc] bg-white px-4 py-4 xl:border-l xl:border-t-0"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Ringkasan</h2><button type="button" onClick={() => setSummaryOpen(false)} aria-label="Tutup ringkasan"><X size={18}/></button></div><div className="relative mt-4 aspect-[1.25] overflow-hidden rounded bg-[#e8eeeb]">{active.thumbnailUrl ? <Image src={active.thumbnailUrl} alt={active.filename} fill unoptimized sizes="260px" className="object-cover grayscale"/> : <ImageIcon size={34} className="m-auto mt-16"/>}</div><h3 className="mt-3 truncate font-bold">{active.filename}</h3><p className="mt-1 text-xs text-[#607076]">{dateLabel(active.capturedAt)} · {timeLabel(active.capturedAt)}</p><p className="mt-2 flex items-center gap-2 text-xs"><Camera size={15}/>{active.camera || 'Kamera belum ada'}</p><p className="mt-2 flex items-center gap-2 text-xs"><MapPin size={15}/>{active.location || 'Lokasi belum ada'}</p><span className="mt-3 inline-flex rounded bg-[#dff1eb] px-2 py-1 text-xs text-[#075f52]">{active.inIssue ? 'Dalam Issue' : 'LIVE'}</span><div className="mt-5 grid gap-2"><Link href={`/photos/${active.id}`} className="rounded bg-[#076b5c] px-3 py-2 text-center text-xs font-semibold text-white">Buka Detail</Link><Link href={`/photos/${active.id}`} className="flex items-center justify-center gap-2 rounded border border-[#0b6e5d] px-3 py-2 text-xs font-semibold text-[#0b6e5d]"><BookOpen size={15}/>Tambahkan ke Issue</Link></div><div className="mt-5 border-t border-[#e2e6e3] pt-4"><h4 className="text-xs font-bold">Metadata EXIF</h4><dl className="mt-2 grid grid-cols-[80px_1fr] gap-y-1 text-[11px] text-[#556368]"><dt>Kamera</dt><dd>{active.camera || '—'}</dd><dt>Lensa</dt><dd>{active.lens || '—'}</dd><dt>ISO</dt><dd>{active.iso ?? '—'}</dd><dt>Aperture</dt><dd>{active.aperture || '—'}</dd><dt>Shutter</dt><dd>{active.shutter || '—'}</dd><dt>Focal</dt><dd>{active.focal || '—'}</dd><dt>Lokasi</dt><dd>{active.latitude != null && active.longitude != null ? `${active.latitude.toFixed(4)}, ${active.longitude.toFixed(4)}` : '—'}</dd></dl></div></aside>}
    </div>

    <div className="sticky bottom-0 z-30 flex min-h-13 flex-wrap items-center gap-3 border-t border-[#dbe0dc] bg-white px-5 py-2 text-xs shadow-[0_-4px_12px_#1723290a]"><label className="flex items-center gap-2"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : items.map(item => item.id))} className="accent-[#076b5c]"/>Pilih semua di halaman</label><span className="border-l border-[#dce2de] pl-3 font-bold">{selected.length} foto dipilih</span>{selected.length === 1 && <Link href={`/photos/${selected[0]}`} className="ml-2 flex items-center gap-1 text-[#075f52]"><BookOpen size={15}/>Buka foto terpilih</Link>}<div className="ml-auto flex items-center gap-2 text-[#5e6c70]"><span>Menampilkan {total ? (filters.page - 1) * 50 + 1 : 0}–{Math.min(filters.page * 50, total)} dari {total.toLocaleString('id-ID')}</span>{filters.page > 1 && <Link href={link({ page: String(filters.page - 1) })} aria-label="Halaman sebelumnya" className="flex h-7 w-7 items-center justify-center rounded border border-[#d7dfda]"><ArrowLeft size={15}/></Link>}{filters.page * 50 < total && <Link href={link({ page: String(filters.page + 1) })} aria-label="Halaman berikutnya" className="flex h-7 w-7 items-center justify-center rounded border border-[#d7dfda]"><ArrowRight size={15}/></Link>}</div></div>
  </div>;
}
