'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, Download, FileText, Folder, HardDrive, ImageIcon, Plus, Search, XCircle } from 'lucide-react';

export type ImportSessionView = { id: string; source: string; status: string; startedAt: string; completedAt: string | null; imported: number; duplicate: number; failed: number; bytes: number };
const number = (value: number) => value.toLocaleString('id-ID');
const size = (bytes: number) => bytes >= 1024 ** 3 ? `${(bytes / 1024 ** 3).toLocaleString('id-ID', { maximumFractionDigits: 1 })} GB` : bytes >= 1024 ** 2 ? `${(bytes / 1024 ** 2).toLocaleString('id-ID', { maximumFractionDigits: 1 })} MB` : `${number(bytes)} B`;
const date = (value: string) => new Date(value).toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta', day: '2-digit', month: 'short', year: 'numeric' });
const time = (value: string) => new Date(value).toLocaleTimeString('id-ID', { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit' });
const statusLabel = (value: string) => value === 'Completed' ? 'Berhasil' : value === 'CompletedWithWarnings' ? 'Selesai dengan catatan' : value === 'Processing' ? 'Diproses' : value === 'Cancelled' ? 'Dibatalkan' : 'Gagal';
const statusStyle = (value: string) => value === 'Completed' ? 'bg-[#e5f2ec] text-[#096553]' : value === 'CompletedWithWarnings' ? 'bg-[#fff1dc] text-[#a56415]' : value === 'Processing' ? 'bg-[#e7eef5] text-[#47647b]' : 'bg-[#ffe8e8] text-[#ad3030]';

export function ImportHistoryWorkspace({ sessions }: { sessions: ImportSessionView[] }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('');
  const [source, setSource] = useState('');
  const [sort, setSort] = useState('newest');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [page, setPage] = useState(1);
  const [perPage, setPerPage] = useState(10);
  const [selected, setSelected] = useState<string[]>([]);
  const [report, setReport] = useState<string | null>(null);
  const now = new Date();
  const month = now.toLocaleDateString('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit' });
  const monthly = sessions.filter(session => new Date(session.startedAt).toLocaleDateString('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit' }) === month);
  const monthImported = monthly.reduce((sum, item) => sum + item.imported, 0);
  const monthDuplicate = monthly.reduce((sum, item) => sum + item.duplicate, 0);
  const monthFailed = monthly.reduce((sum, item) => sum + item.failed, 0);
  const monthBytes = monthly.reduce((sum, item) => sum + item.bytes, 0);
  const sources = [...new Set(sessions.map(item => item.source))];
  const filtered = useMemo(() => sessions.filter(item => {
    const text = `${item.source} ${item.id}`.toLowerCase();
    const day = new Date(item.startedAt).toLocaleDateString('en-CA', { timeZone: 'Asia/Jakarta' });
    return (!query || text.includes(query.toLowerCase())) && (!status || item.status === status) && (!source || item.source === source) && (!from || day >= from) && (!to || day <= to);
  }).sort((a, b) => sort === 'oldest' ? a.startedAt.localeCompare(b.startedAt) : b.startedAt.localeCompare(a.startedAt)), [sessions, query, status, source, from, to, sort]);
  const shown = filtered.slice((page - 1) * perPage, page * perPage);
  const chosen = sessions.filter(item => selected.includes(item.id));
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const week = [0, 0, 0, 0, 0];
  for (const item of monthly) { const day = Number(new Date(item.startedAt).toLocaleDateString('en-US', { timeZone: 'Asia/Jakarta', day: 'numeric' })); week[Math.min(4, Math.floor((day - 1) / 7))] += item.imported; }
  const maxWeek = Math.max(...week, 1);
  const sourceCounts = sources.map(name => ({ name, count: monthly.filter(item => item.source === name).length })).sort((a, b) => b.count - a.count);
  const activeReport = sessions.find(item => item.id === report);

  function downloadReport() {
    if (!chosen.length) return;
    const rows = [['ID Sesi', 'Tanggal', 'Sumber', 'Status', 'Berhasil', 'Duplikat', 'Gagal', 'Ukuran (byte)'], ...chosen.map(item => [item.id, item.startedAt, item.source, item.status, item.imported, item.duplicate, item.failed, item.bytes].map(String))];
    const csv = rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'riwayat-import.csv'; anchor.click(); URL.revokeObjectURL(url);
  }

  return <div className="-mx-7 -mb-5 grid min-h-[calc(100dvh-88px)] grid-cols-1 bg-[#fdfdfb] xl:grid-cols-[minmax(0,1fr)_300px] max-sm:-mx-4">
    <main className="min-w-0 px-4 py-4 lg:px-6"><div className="flex items-center gap-2 text-xs"><Link href="/import" className="text-[#116a5c]">« Import</Link><span>/</span><strong>Riwayat Import</strong></div><h1 className="mt-2 font-serif text-[clamp(30px,2.6vw,42px)] font-bold leading-none">Riwayat Import</h1><p className="mt-1 text-sm text-[#596d7a]">Lihat seluruh aktivitas impor dan buka laporan setiap sesi.</p>
      <div className="mt-5 grid grid-cols-2 gap-2 lg:grid-cols-4">{[{ icon: FileText, value: monthly.length, label: 'Sesi Import', sub: 'bulan ini', tone: 'text-[#0a6c58]' }, { icon: ImageIcon, value: monthImported, label: 'Foto', sub: 'berhasil diimpor', tone: 'text-[#0a6c58]' }, { icon: Folder, value: monthDuplicate, label: 'Duplikat', sub: 'terdeteksi', tone: 'text-[#344a60]' }, { icon: AlertTriangle, value: monthFailed, label: 'Gagal', sub: 'perlu ditangani', tone: 'text-[#b83636]' }].map(item => <div key={item.label} className="flex min-h-25 items-center gap-4 rounded border border-[#dce3e4] bg-white px-4"><item.icon size={31} className={item.tone} strokeWidth={1.6}/><div><strong className="block font-serif text-2xl leading-none">{number(item.value)}</strong><span className="mt-1 block text-sm font-medium">{item.label}</span><small className="block text-xs text-[#657579]">{item.sub}</small></div></div>)}</div><p className="mt-2 text-xs text-[#596d7a]">Total penyimpanan bulan ini: <strong>{size(monthBytes)}</strong></p>
      <section className="mt-5 rounded border border-[#dce3e4] bg-white p-3"><h2 className="font-serif text-xl font-bold">Semua Sesi</h2><div className="mt-3 grid gap-2 sm:grid-cols-[minmax(180px,1fr)_145px_150px_150px_140px]"><label className="relative"><span className="sr-only">Cari sesi</span><Search className="absolute left-2.5 top-2.5 text-[#5d7180]" size={16}/><input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="Cari sumber atau ID sesi..." className="h-9 w-full rounded border border-[#d0dce4] pl-8 pr-2 text-xs"/></label><div className="flex gap-1"><input type="date" value={from} onChange={event => { setFrom(event.target.value); setPage(1); }} aria-label="Dari tanggal" className="h-9 min-w-0 w-full rounded border border-[#d0dce4] px-1 text-xs"/><input type="date" value={to} onChange={event => { setTo(event.target.value); setPage(1); }} aria-label="Sampai tanggal" className="h-9 min-w-0 w-full rounded border border-[#d0dce4] px-1 text-xs"/></div><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }} aria-label="Filter status" className="h-9 rounded border border-[#d0dce4] px-2 text-xs"><option value="">Semua Status</option>{[...new Set(sessions.map(item => item.status))].map(value => <option key={value} value={value}>{statusLabel(value)}</option>)}</select><select value={source} onChange={event => { setSource(event.target.value); setPage(1); }} aria-label="Filter sumber" className="h-9 rounded border border-[#d0dce4] px-2 text-xs"><option value="">Semua Sumber</option>{sources.map(value => <option key={value} value={value}>{value}</option>)}</select><select value={sort} onChange={event => setSort(event.target.value)} aria-label="Urutan sesi" className="h-9 rounded border border-[#d0dce4] px-2 text-xs"><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select></div>
        <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[800px] border-collapse text-left text-xs"><thead className="bg-[#f5f8f6] text-[#52666c]"><tr><th className="p-2"><input type="checkbox" aria-label="Pilih semua sesi di halaman" checked={shown.length > 0 && shown.every(item => selected.includes(item.id))} onChange={event => setSelected(current => event.target.checked ? [...new Set([...current, ...shown.map(item => item.id)])] : current.filter(id => !shown.some(item => item.id === id)))} /></th><th className="p-2">Tanggal &amp; Waktu</th><th className="p-2">Nama Sesi / Sumber</th><th className="p-2">Status</th><th className="p-2 text-right">File</th><th className="p-2 text-right">Berhasil</th><th className="p-2 text-right">Duplikat</th><th className="p-2 text-right">Gagal</th><th className="p-2 text-right">Ukuran</th><th className="p-2">Tindakan</th></tr></thead><tbody>{shown.map(item => <tr key={item.id} className={`border-t border-[#e3e8e7] ${selected.includes(item.id) ? 'bg-[#f0f8f4]' : ''}`}><td className="p-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} aria-label={`Pilih sesi ${item.id}`}/></td><td className="whitespace-nowrap p-2">{date(item.startedAt)}<span className="block text-[#657579]">{time(item.startedAt)}</span></td><td className="max-w-45 p-2"><strong className="block truncate">{item.source}</strong><span className="block truncate font-mono text-[10px] text-[#657579]">{item.id}</span></td><td className="p-2"><span className={`inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[10px] ${statusStyle(item.status)}`}>{statusLabel(item.status)}</span></td><td className="p-2 text-right">{number(item.imported + item.duplicate + item.failed)}</td><td className="p-2 text-right">{number(item.imported)}</td><td className="p-2 text-right">{number(item.duplicate)}</td><td className="p-2 text-right">{number(item.failed)}</td><td className="whitespace-nowrap p-2 text-right">{size(item.bytes)}</td><td className="p-2"><button type="button" onClick={() => setReport(item.id)} className="whitespace-nowrap rounded border border-[#cad9e2] px-2 py-1.5 text-[11px] text-[#25435b]">Lihat Laporan</button></td></tr>)}</tbody></table>{!shown.length && <p className="py-12 text-center text-sm text-[#657579]">Belum ada sesi yang cocok.</p>}</div></section>
      <div className="mt-3 flex flex-wrap items-center gap-3 rounded bg-[#075d4f] px-4 py-3 text-xs text-white"><strong>{selected.length} sesi dipilih</strong><button type="button" onClick={downloadReport} disabled={!selected.length} className="flex items-center gap-1 rounded border border-white/60 px-3 py-1.5 disabled:opacity-50"><Download size={14}/>Unduh Laporan CSV</button><span className="ml-auto">{filtered.length ? `${(page - 1) * perPage + 1}–${Math.min(page * perPage, filtered.length)}` : '0'} dari {filtered.length} sesi</span><select value={perPage} onChange={event => { setPerPage(Number(event.target.value)); setPage(1); }} aria-label="Sesi per halaman" className="rounded bg-white px-2 py-1.5 text-[#172329]"><option value={10}>10 per halaman</option><option value={25}>25 per halaman</option><option value={50}>50 per halaman</option></select><button type="button" onClick={() => setPage(value => Math.max(1, value - 1))} disabled={page === 1} aria-label="Halaman sebelumnya" className="rounded border border-white/50 p-1 disabled:opacity-40"><ArrowLeft size={17}/></button><button type="button" onClick={() => setPage(value => value + 1)} disabled={page * perPage >= filtered.length} aria-label="Halaman berikutnya" className="rounded border border-white/50 p-1 disabled:opacity-40"><ArrowRight size={17}/></button></div>
    </main>
    <aside className="space-y-3 border-t border-[#dce3e4] bg-white p-4 xl:border-l xl:border-t-0"><Link href="/import" className="flex h-10 items-center justify-center gap-2 rounded bg-[#076b5c] text-sm font-semibold text-white"><Plus size={19}/>Import Foto</Link><section className="rounded border border-[#dce3e4] p-4"><h2 className="font-serif text-lg font-bold">Aktivitas Bulan Ini</h2><p className="mt-2"><strong className="font-serif text-3xl">{number(monthImported)}</strong><span className="ml-2 text-sm">foto</span></p><div className="mt-4 flex h-30 items-end gap-2 border-b border-[#e0e7e4]">{week.map((value, index) => <div key={index} className="flex flex-1 flex-col items-center justify-end"><span className="mb-1 text-[10px]">{number(value)}</span><div className="w-full bg-[#0b705c]" style={{ height: `${Math.max(3, value / maxWeek * 90)}px` }}/></div>)}</div><div className="mt-1 flex gap-2 text-center text-[10px] text-[#62747a]">{week.map((_, index) => <span key={index} className="flex-1">M{index + 1}</span>)}</div></section><section className="rounded border border-[#dce3e4] p-4"><h2 className="font-serif text-lg font-bold">Status Import</h2>{[{ label: 'Berhasil', value: monthly.filter(item => item.status === 'Completed').length, icon: CheckCircle2, color: 'bg-[#0b705c]' }, { label: 'Dengan catatan', value: monthly.filter(item => item.status === 'CompletedWithWarnings').length, icon: AlertTriangle, color: 'bg-[#ca7a11]' }, { label: 'Diproses', value: monthly.filter(item => item.status === 'Processing').length, icon: HardDrive, color: 'bg-[#5f7889]' }].map(item => <div key={item.label} className="mt-3 flex items-center gap-2 text-xs"><item.icon size={18}/><div className="flex-1"><div className="flex justify-between"><span>{item.label}</span><span>{item.value} sesi</span></div><div className="mt-1 h-1.5 rounded bg-[#e4e8e9]"><div className={`h-full rounded ${item.color}`} style={{ width: `${monthly.length ? item.value / monthly.length * 100 : 0}%` }}/></div></div></div>)}</section><section className="rounded border border-[#dce3e4] p-4"><h2 className="font-serif text-lg font-bold">Sumber Teratas</h2>{sourceCounts.length ? sourceCounts.map(item => <div key={item.name} className="mt-3 flex items-center gap-2 text-xs"><Folder size={17}/><div className="flex-1"><div className="flex justify-between"><span>{item.name}</span><span>{monthly.length ? Math.round(item.count / monthly.length * 100) : 0}%</span></div><div className="mt-1 h-1.5 rounded bg-[#e4e8e9]"><div className="h-full rounded bg-[#0b705c]" style={{ width: `${monthly.length ? item.count / monthly.length * 100 : 0}%` }}/></div></div></div>) : <p className="mt-3 text-xs text-[#657579]">Belum ada sumber bulan ini.</p>}</section><div className="flex items-center gap-2 rounded border border-[#dce3e4] p-4 text-xs"><CheckCircle2 size={22} className="text-[#0b705c]"/><span><strong className="block text-sm">Database aktif</strong>Riwayat disimpan di SQLite lokal</span></div></aside>
    {activeReport && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#142a2a88] p-4" role="dialog" aria-modal="true" aria-label="Laporan sesi import"><div className="w-full max-w-md rounded bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Laporan Sesi</h2><button type="button" onClick={() => setReport(null)} aria-label="Tutup laporan"><XCircle size={22}/></button></div><p className="mt-2 break-all font-mono text-xs text-[#657579]">{activeReport.id}</p><dl className="mt-4 grid grid-cols-2 gap-y-2 text-sm"><dt>Mulai</dt><dd>{date(activeReport.startedAt)} {time(activeReport.startedAt)}</dd><dt>Selesai</dt><dd>{activeReport.completedAt ? `${date(activeReport.completedAt)} ${time(activeReport.completedAt)}` : 'Masih diproses'}</dd><dt>Sumber</dt><dd>{activeReport.source}</dd><dt>Status</dt><dd>{statusLabel(activeReport.status)}</dd><dt>Berhasil</dt><dd>{number(activeReport.imported)}</dd><dt>Duplikat</dt><dd>{number(activeReport.duplicate)}</dd><dt>Gagal</dt><dd>{number(activeReport.failed)}</dd><dt>Ukuran</dt><dd>{size(activeReport.bytes)}</dd></dl><button type="button" onClick={() => { setSelected(current => current.includes(activeReport.id) ? current : [...current, activeReport.id]); setReport(null); }} className="mt-5 w-full rounded bg-[#076b5c] px-4 py-2 text-sm text-white">Pilih untuk unduh laporan</button></div></div>}
  </div>;
}
