'use client';

import { useState } from 'react';
import { ArrowDown, ArrowUp, ImageIcon, Plus, Trash2 } from 'lucide-react';

type Photo = { id: string; filename: string; thumbnailId: string | null };
type Saved = { photoId: string; caption: string | null; altText: string | null };
export function IssueEditor({ issue, available, saved, action }: { issue: { title: string; subtitle: string; description: string }; available: Photo[]; saved: Saved[]; action: (form: FormData) => Promise<void> }) {
  const [selected, setSelected] = useState(saved.map(item => item.photoId));
  const [query, setQuery] = useState('');
  const savedValues = new Map(saved.map(item => [item.photoId, item]));
  const byId = new Map(available.map(item => [item.id, item]));
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= selected.length) return; setSelected(items => { const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy; }); }
  return <form action={action} className="space-y-5"><input type="hidden" name="photoIds" value={JSON.stringify(selected)}/><section className="grid gap-4 rounded border border-[#d9dfdc] bg-white p-5 md:grid-cols-2"><div><label htmlFor="issue-title" className="mb-1 block text-sm font-semibold">Judul</label><input id="issue-title" name="title" required maxLength={150} defaultValue={issue.title} className="w-full rounded border border-[#cbd8d1] px-3 py-2"/></div><div><label htmlFor="issue-subtitle" className="mb-1 block text-sm font-semibold">Subtitle</label><input id="issue-subtitle" name="subtitle" maxLength={250} defaultValue={issue.subtitle} className="w-full rounded border border-[#cbd8d1] px-3 py-2"/></div><div className="md:col-span-2"><label htmlFor="issue-description" className="mb-1 block text-sm font-semibold">Deskripsi</label><textarea id="issue-description" name="description" rows={3} maxLength={5000} defaultValue={issue.description} className="w-full rounded border border-[#cbd8d1] px-3 py-2"/></div></section>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.9fr)]"><section className="rounded border border-[#d9dfdc] bg-white p-5"><h2 className="text-lg font-bold">Pilih dari Arsip</h2><p className="text-xs text-[#65747a]">Maksimal 100 foto per Issue.</p><input value={query} onChange={event => setQuery(event.target.value)} aria-label="Cari foto" placeholder="Cari filename..." className="mt-4 w-full rounded border border-[#cbd8d1] px-3 py-2 text-sm"/><div className="mt-4 grid max-h-100 grid-cols-2 gap-3 overflow-auto sm:grid-cols-3">{available.filter(photo => photo.filename.toLowerCase().includes(query.toLowerCase())).map(photo => <div key={photo.id} className="overflow-hidden rounded border border-[#d9dfdc]"><div className="aspect-[1.4] bg-[#e7ece9]">{photo.thumbnailId ? <img src={`/api/assets/${photo.thumbnailId}`} alt="" className="h-full w-full object-cover"/> : <ImageIcon size={28} className="m-auto pt-4"/>}</div><div className="p-2"><p className="truncate text-xs" title={photo.filename}>{photo.filename}</p><button type="button" disabled={selected.includes(photo.id) || selected.length >= 100} onClick={() => setSelected(items => [...items, photo.id])} className="mt-2 flex items-center gap-1 text-xs text-[#116a5c] disabled:opacity-40"><Plus size={14}/>Tambah</button></div></div>)}</div></section>
      <section className="rounded border border-[#d9dfdc] bg-white p-5"><h2 className="text-lg font-bold">Susunan Halaman <span className="text-sm font-normal text-[#65747a]">({selected.length} foto)</span></h2><p className="text-xs text-[#65747a]">Halaman pertama menjadi sampul.</p><div className="mt-4 max-h-140 space-y-3 overflow-auto">{selected.map((id, index) => { const photo = byId.get(id); return <div key={id} className="rounded border border-[#d9dfdc] p-3"><div className="flex items-center gap-3"><span className="w-6 shrink-0 text-sm font-bold text-[#116a5c]">{index + 1}</span><div className="h-14 w-18 shrink-0 overflow-hidden rounded bg-[#e7ece9]">{photo?.thumbnailId && <img src={`/api/assets/${photo.thumbnailId}`} alt="" className="h-full w-full object-cover"/>}</div><span className="min-w-0 flex-1 truncate text-sm">{photo?.filename ?? id}</span><div className="flex gap-1"><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label="Naikkan halaman" className="p-1 disabled:opacity-30"><ArrowUp size={16}/></button><button type="button" onClick={() => move(index, 1)} disabled={index === selected.length - 1} aria-label="Turunkan halaman" className="p-1 disabled:opacity-30"><ArrowDown size={16}/></button><button type="button" onClick={() => setSelected(items => items.filter(item => item !== id))} aria-label="Hapus dari Issue" className="p-1 text-red-600"><Trash2 size={16}/></button></div></div><div className="mt-3 grid gap-2"><input name={`caption-${id}`} defaultValue={savedValues.get(id)?.caption ?? ''} placeholder="Caption (opsional)" className="w-full rounded border border-[#cbd8d1] px-2 py-1.5 text-xs"/><input name={`alt-${id}`} defaultValue={savedValues.get(id)?.altText ?? ''} placeholder="Alt text untuk aksesibilitas" className="w-full rounded border border-[#cbd8d1] px-2 py-1.5 text-xs"/></div></div>; })}{!selected.length && <p className="rounded bg-[#f1f5f2] p-5 text-center text-sm text-[#65747a]">Pilih foto dari Arsip untuk mulai menyusun.</p>}</div></section></div>
    <div className="flex justify-end border-t border-[#d9dfdc] pt-4"><button className="rounded bg-[#116a5c] px-6 py-2.5 text-sm font-semibold text-white">Simpan Draft</button></div>
  </form>;
}
