'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarDays, Grid2X2, ImageIcon, List, MapPin, Plus, Search, Trash2, X } from 'lucide-react';
import { addToLiveAction, removeFromLiveAction } from '@/app/(main)/live/actions';

type Item = { id: string; filename: string; status: string; thumbnailId: string | null; location: string | null; date: string; time: string };
export function LiveWorkspace({ current, available }: { current: Item[]; available: Item[] }) {
  const router = useRouter();
  const [mode, setMode] = useState<'live' | 'archive'>('live');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('');
  const [list, setList] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [pending, startTransition] = useTransition();
  const items = mode === 'live' ? current : available;
  const filtered = useMemo(() => items.filter(item => (!query || `${item.filename} ${item.location ?? ''}`.toLowerCase().includes(query.toLowerCase())) && (!status || item.status === status)), [items, query, status]);
  const selectedItems = items.filter(item => selected.includes(item.id));
  const allSelected = filtered.length > 0 && filtered.every(item => selected.includes(item.id));
  function toggle(id: string) { setSelected(value => value.includes(id) ? value.filter(item => item !== id) : [...value, id]); }
  function changeMode(value: 'live' | 'archive') { setMode(value); setSelected([]); setQuery(''); setStatus(''); }
  function submit() { if (!selected.length || pending) return; startTransition(async () => { try { if (mode === 'live') await removeFromLiveAction(selected); else await addToLiveAction(selected); setSelected([]); router.refresh(); } catch (error) { alert(error instanceof Error ? error.message : 'Tindakan gagal.'); } }); }
  return <div className="grid min-h-130 gap-3 xl:grid-cols-[minmax(0,1fr)_275px]">
    <section className="min-w-0"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={() => changeMode('live')} className={`rounded px-4 py-2 text-sm ${mode === 'live' ? 'bg-[#116a5c] text-white' : 'border border-[#d5dfd9] bg-white'}`}>Foto LIVE ({current.length})</button><button onClick={() => changeMode('archive')} className={`rounded px-4 py-2 text-sm ${mode === 'archive' ? 'bg-[#116a5c] text-white' : 'border border-[#d5dfd9] bg-white'}`}>Tambah dari Arsip ({available.length})</button></div><div className="flex overflow-hidden rounded border border-[#d5dfd9]"><button title="Tampilan grid" aria-pressed={!list} onClick={() => setList(false)} className={`p-2 ${!list ? 'bg-[#e5f2ec] text-[#116a5c]' : 'bg-white'}`}><Grid2X2 size={19}/></button><button title="Tampilan daftar" aria-pressed={list} onClick={() => setList(true)} className={`p-2 ${list ? 'bg-[#e5f2ec] text-[#116a5c]' : 'bg-white'}`}><List size={19}/></button></div></div>
      <div className="mb-3 flex flex-wrap gap-2"><label className="relative min-w-45 flex-1"><span className="sr-only">Cari foto</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#69817a]" size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Cari filename atau lokasi..." className="h-10 w-full rounded border border-[#d5dfd9] bg-white pl-9 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-[#116a5c]"/></label><select aria-label="Filter status" value={status} onChange={event => setStatus(event.target.value)} className="h-10 rounded border border-[#d5dfd9] bg-white px-3 text-sm"><option value="">Semua status</option><option value="Ready">Siap</option><option value="Need Review">Perlu diperiksa</option><option value="Private">Private</option></select></div>
      {filtered.length ? <div className={list ? 'space-y-2' : 'grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4'}>{filtered.map(item => <div key={item.id} className={`overflow-hidden rounded border bg-white ${selected.includes(item.id) ? 'border-[#116a5c] ring-1 ring-[#116a5c]' : 'border-[#d9e0dc]'} ${list ? 'flex items-center gap-3 p-2' : ''}`}><button type="button" aria-label={`${selected.includes(item.id) ? 'Batalkan pilihan' : 'Pilih'} ${item.filename}`} aria-pressed={selected.includes(item.id)} onClick={() => toggle(item.id)} className={`relative block overflow-hidden bg-[#e7ece9] ${list ? 'h-16 w-22 shrink-0 rounded' : 'aspect-[1.6] w-full'}`}>{item.thumbnailId ? <img src={`/api/assets/${item.thumbnailId}`} alt="" className="h-full w-full object-cover" loading="lazy"/> : <span className="flex h-full items-center justify-center text-[#91a5a0]"><ImageIcon size={28}/></span>}<span className={`absolute left-2 top-2 flex h-5 w-5 items-center justify-center rounded border border-white shadow ${selected.includes(item.id) ? 'bg-[#116a5c] text-white' : 'bg-white'}`}>{selected.includes(item.id) && '✓'}</span></button><div className="min-w-0 p-2 text-xs"><div className="flex items-center justify-between gap-1"><Link href={`/photos/${item.id}`} className="truncate font-semibold hover:underline" title={item.filename}>{item.filename}</Link><span className={`rounded px-1.5 py-0.5 text-[10px] ${item.status === 'Ready' ? 'bg-[#dff1e7] text-[#145c4f]' : 'bg-[#fff0d9] text-[#926419]'}`}>{item.status === 'Need Review' ? 'PERIKSA' : item.status}</span></div><p className="mt-1 flex items-center gap-1 text-[#677a7c]"><CalendarDays size={12}/>{item.date}{item.time && ` · ${item.time}`}</p><p className="mt-1 flex items-center gap-1 truncate text-[#677a7c]"><MapPin size={12}/>{item.location ?? 'Lokasi belum ada'}</p></div></div>)}</div> : <div className="rounded border border-[#d9e0dc] bg-white py-18 text-center text-sm text-[#687b79]"><ImageIcon size={35} className="mx-auto mb-3"/>{mode === 'live' && !current.length ? 'LIVE masih kosong. Tambahkan foto dari Arsip.' : 'Tidak ada foto yang cocok.'}</div>}
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded border border-[#d9e0dc] bg-white p-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? selected.filter(id => !filtered.some(item => item.id === id)) : [...new Set([...selected, ...filtered.map(item => item.id)])])} className="accent-[#116a5c]"/>Pilih semua hasil</label><span>{selected.length} dipilih</span><button disabled={!selected.length || pending} onClick={submit} className="flex items-center gap-2 rounded border border-[#116a5c] px-4 py-2 text-[#116a5c] disabled:opacity-40">{mode === 'live' ? <Trash2 size={16}/> : <Plus size={16}/ >}{pending ? 'Memproses...' : mode === 'live' ? 'Hapus dari LIVE' : 'Tambahkan ke LIVE'}</button></div>
    </section>
    <aside className="rounded border border-[#d9e0dc] bg-white p-4"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Pilihan</h2><button aria-label="Kosongkan pilihan" onClick={() => setSelected([])}><X size={18}/></button></div><p className="text-sm text-[#66787a]">{selected.length} foto dipilih</p><div className="mt-4 max-h-100 space-y-3 overflow-y-auto">{selectedItems.map(item => <div key={item.id} className="flex items-center gap-2"><div className="h-13 w-13 shrink-0 overflow-hidden rounded bg-[#e7ece9]">{item.thumbnailId ? <img src={`/api/assets/${item.thumbnailId}`} alt="" className="h-full w-full object-cover"/> : <ImageIcon className="m-auto mt-3" size={20}/>}</div><div className="min-w-0 flex-1 text-xs"><p className="truncate font-semibold">{item.filename}</p><p className="text-[#677a7c]">{item.date}</p></div><button aria-label={`Hapus ${item.filename} dari pilihan`} onClick={() => toggle(item.id)}><X size={16}/></button></div>)}</div><div className="mt-5 border-t border-[#d9e0dc] pt-4"><strong>{selected.length}</strong> / {items.length} foto<div className="mt-2 h-2 rounded-full bg-[#e3e8e5]"><div className="h-full rounded-full bg-[#116a5c]" style={{ width: `${items.length ? selected.length / items.length * 100 : 0}%` }}/></div><p className="mt-3 text-xs text-[#66787a]">{mode === 'live' ? 'Menghapus dari LIVE tidak menghapus original.' : 'Foto tetap tersimpan di Arsip.'}</p><button disabled={!selected.length || pending} onClick={submit} className="mt-4 flex w-full items-center justify-center gap-2 rounded bg-[#116a5c] px-4 py-2.5 text-sm text-white disabled:opacity-40">{mode === 'live' ? 'Hapus dari LIVE' : 'Tambahkan ke LIVE'}</button></div></aside>
  </div>;
}
