'use client';

import { useState } from 'react';
import { Aperture, CheckCircle2, Database, HardDrive, LockKeyhole, Monitor, Moon, Save, Shield, Sun, UserRound } from 'lucide-react';
import type { AppPreferences } from '@/lib/app-preferences';

const size = (bytes: number) => bytes >= 1024 ** 3 ? `${(bytes / 1024 ** 3).toLocaleString('id-ID', { maximumFractionDigits: 1 })} GB` : bytes >= 1024 ** 2 ? `${(bytes / 1024 ** 2).toLocaleString('id-ID', { maximumFractionDigits: 1 })} MB` : `${(bytes / 1024).toLocaleString('id-ID', { maximumFractionDigits: 1 })} KB`;
const accents = ['#0b6b5a', '#789489', '#2e689d', '#7050a0', '#b34c39', '#bd8622'];

export function SettingsWorkspace({ preferences, photographer, databasePath, databaseBytes, mediaPath, mediaBytes, journalMode, lastBackup, saved, integrity, backupSaved, saveAction, integrityAction, backupAction }: { preferences: AppPreferences; photographer: string; databasePath: string; databaseBytes: number; mediaPath: string; mediaBytes: number; journalMode: string; lastBackup: { name: string; createdAt: string; bytes: number } | null; saved: boolean; integrity: string | null; backupSaved: boolean; saveAction: (form: FormData) => Promise<void>; integrityAction: () => Promise<void>; backupAction: () => Promise<void> }) {
  const [dirty, setDirty] = useState(false);
  const [theme, setTheme] = useState(preferences.theme);
  const [accent, setAccent] = useState(preferences.accent);
  const [gridSize, setGridSize] = useState(preferences.gridSize);
  const mark = () => setDirty(true);
  return <div className="-mx-7 -mb-5 grid min-h-[calc(100dvh-88px)] grid-cols-1 bg-[#fcfcfa] xl:grid-cols-[210px_minmax(0,1fr)] max-sm:-mx-4"><aside className="hidden border-r border-[#dce3de] bg-white px-3 py-5 xl:block"><h2 className="px-3 text-xs font-bold tracking-[.15em] text-[#647570]">PENGATURAN</h2><nav className="mt-4 space-y-1 text-sm">{[{ href: '#profile', label: 'Profil Arsip', icon: UserRound }, { href: '#appearance', label: 'Tampilan', icon: Monitor }, { href: '#privacy', label: 'Metadata & Privasi', icon: Shield }, { href: '#storage', label: 'Penyimpanan', icon: HardDrive }, { href: '#database', label: 'Database SQLite', icon: Database }, { href: '#backup', label: 'Backup & Pemulihan', icon: Database }].map((item, index) => <a key={item.href} href={item.href} className={`flex items-center gap-3 rounded px-3 py-2.5 hover:bg-[#e8f1ed] ${index === 0 ? 'bg-[#e2f0e9] font-semibold text-[#0b6556]' : ''}`}><item.icon size={19}/>{item.label}</a>)}</nav></aside><div className="min-w-0 px-4 pb-5 pt-4 lg:px-6"><header className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h1 className="text-[32px] font-extrabold leading-none">Pengaturan</h1><p className="mt-1 text-sm text-[#65747a]">Kelola identitas, privasi, dan penyimpanan arsip.</p></div><span className={`text-xs ${dirty ? 'text-[#ad741b]' : 'text-[#0b6b59]'}`}>{dirty ? '● Perubahan belum disimpan' : saved ? '✓ Pengaturan tersimpan' : 'Semua perubahan tersimpan'}</span></header>
      <form action={saveAction} onChange={mark} onReset={() => { setDirty(false); setTheme(preferences.theme); setAccent(preferences.accent); setGridSize(preferences.gridSize); }} className="grid gap-3 lg:grid-cols-2"><div className="space-y-3"><section id="profile" className="rounded border border-[#dce3de] bg-white p-4"><h2 className="text-lg font-bold">Profil Arsip</h2><div className="mt-3 grid gap-4 sm:grid-cols-[110px_1fr]"><div className="flex h-27 items-center justify-center rounded border border-[#e5e9e5] bg-[#faf9f6]"><Aperture size={68} className="text-[#0b6556]" strokeWidth={1.3}/></div><div className="space-y-2"><label className="block text-xs font-medium">Nama Arsip<input name="archiveName" defaultValue={preferences.archiveName} maxLength={120} required className="mt-1 w-full rounded border border-[#cbd6d1] px-3 py-2 text-sm"/></label><label className="block text-xs font-medium">Nama Fotografer<input name="photographer" defaultValue={photographer} maxLength={120} required className="mt-1 w-full rounded border border-[#cbd6d1] px-3 py-2 text-sm"/></label></div></div><label className="mt-3 block text-xs font-medium">Deskripsi Singkat<textarea name="description" defaultValue={preferences.description} maxLength={500} rows={2} className="mt-1 w-full rounded border border-[#cbd6d1] px-3 py-2 text-sm"/></label><div className="mt-2 grid grid-cols-2 gap-3"><label className="text-xs font-medium">Rentang Tahun<input name="yearRange" defaultValue={preferences.yearRange} maxLength={40} className="mt-1 w-full rounded border border-[#cbd6d1] px-3 py-2 text-sm"/></label><label className="text-xs font-medium">Bahasa Antarmuka<select name="language" defaultValue="id" className="mt-1 w-full rounded border border-[#cbd6d1] bg-white px-3 py-2 text-sm"><option value="id">Bahasa Indonesia</option></select></label></div><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" name="showStats" defaultChecked={preferences.showStats} className="accent-[#0b6b5a]"/>Tampilkan statistik di halaman depan</label></section>
          <section id="appearance" className="rounded border border-[#dce3de] bg-white p-4"><h2 className="text-lg font-bold">Tampilan</h2><p className="mt-3 text-xs font-semibold">Tema Aplikasi</p><div className="mt-1 grid grid-cols-3 overflow-hidden rounded border border-[#cbd6d1] text-xs">{[{ value: 'light', label: 'Terang', icon: Sun }, { value: 'dark', label: 'Gelap', icon: Moon }, { value: 'system', label: 'Sistem', icon: Monitor }].map(item => <label key={item.value} className={`flex cursor-pointer items-center justify-center gap-2 border-l border-[#cbd6d1] px-2 py-2 first:border-l-0 ${theme === item.value ? 'bg-[#0b6b5a] text-white' : ''}`}><input type="radio" name="theme" value={item.value} defaultChecked={preferences.theme === item.value} onChange={() => setTheme(item.value as typeof theme)} className="sr-only"/><item.icon size={16}/>{item.label}</label>)}</div><p className="mt-3 text-xs font-semibold">Warna Aksen</p><div className="mt-2 flex gap-3">{accents.map(value => <label key={value} className={`flex h-7 w-7 cursor-pointer items-center justify-center rounded-full ${accent === value ? 'ring-2 ring-[#0b6b5a] ring-offset-2' : ''}`} style={{ backgroundColor: value }}><input type="radio" name="accent" value={value} defaultChecked={preferences.accent === value} onChange={() => setAccent(value)} className="sr-only"/>{accent === value && <CheckCircle2 size={16} className="text-white"/>}</label>)}</div><p className="mt-4 text-xs font-semibold">Ukuran Grid Default</p><div className="mt-1 grid grid-cols-3 overflow-hidden rounded border border-[#cbd6d1] text-xs">{[{ value: 'small', label: 'Kecil' }, { value: 'medium', label: 'Sedang' }, { value: 'large', label: 'Besar' }].map(item => <label key={item.value} className={`cursor-pointer border-l border-[#cbd6d1] px-2 py-2 text-center first:border-l-0 ${gridSize === item.value ? 'bg-[#0b6b5a] text-white' : ''}`}><input type="radio" name="gridSize" value={item.value} defaultChecked={preferences.gridSize === item.value} onChange={() => setGridSize(item.value as typeof gridSize)} className="sr-only"/>{item.label}</label>)}</div><label className="mt-4 flex items-center gap-2 text-xs"><input type="checkbox" name="monochromeCover" defaultChecked={preferences.monochromeCover} className="accent-[#0b6b5a]"/>Gunakan monokrom untuk sampul PDF</label></section></div>
        <div className="space-y-3"><section id="privacy" className="rounded border border-[#dce3de] bg-white p-4"><h2 className="text-lg font-bold">Metadata &amp; Privasi</h2><div className="mt-3 grid grid-cols-2 items-center gap-2 text-xs"><span>GPS Default</span><select name="gpsDefault" value="private" disabled className="rounded border border-[#cbd6d1] bg-[#f4f7f5] px-3 py-2"><option value="private">Privat</option></select></div><p className="mt-3 flex items-center gap-2 text-xs text-[#0b6657]"><CheckCircle2 size={16}/>EXIF sensitif dihapus dari gambar turunan</p><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" name="showCameraLens" defaultChecked={preferences.showCameraLens} className="accent-[#0b6b5a]"/>Tampilkan kamera &amp; lensa pada Issue publik</label><p className="mt-3 flex items-center gap-2 text-xs text-[#657579]"><LockKeyhole size={15}/>Koordinat tepat tetap privat</p><label className="mt-3 block text-xs">Presisi Lokasi Publik<select name="publicPrecision" defaultValue={preferences.publicPrecision} className="mt-1 w-full rounded border border-[#cbd6d1] bg-white px-3 py-2 text-sm"><option value="city">Kota</option><option value="area">Area</option><option value="exact">Tepat</option></select></label><div className="mt-4 rounded bg-[#edf5f1] p-3 text-xs text-[#496460]">File asli dan GPS privat tidak disajikan sebagai aset publik.</div></section>
          <section id="storage" className="rounded border border-[#dce3de] bg-white p-4"><h2 className="text-lg font-bold">Penyimpanan &amp; SQLite</h2><div className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><div><p className="font-semibold">Lokasi Database</p><p className="mt-1 break-all rounded bg-[#f2f5f3] p-2 font-mono">{databasePath}</p><p className="mt-3 font-semibold">Ukuran Database</p><p>{size(databaseBytes)}</p></div><div><p className="font-semibold">Penggunaan Media</p><p className="mt-1 text-sm">{size(mediaBytes)}</p><div className="mt-1 h-2 rounded bg-[#e0e6e2]"><div className="h-full max-w-full rounded bg-[#0b6b5a]" style={{ width: `${Math.max(2, Math.min(100, mediaBytes / (50 * 1024 ** 3) * 100))}%` }}/></div><p className="mt-3 font-semibold">Lokasi Media</p><p className="mt-1 break-all rounded bg-[#f2f5f3] p-2 font-mono">{mediaPath}</p></div></div><div id="database" className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[#dce3de] pt-3 text-xs"><span><span className="font-semibold">WAL Status</span><br/>{journalMode.toUpperCase()} Mode</span><button type="submit" formAction={integrityAction} className="rounded border border-[#0b6b5a] px-3 py-2 text-[#0b6b5a]">Periksa Integritas</button></div>{integrity && <p role="status" className={`mt-2 text-xs ${integrity === 'ok' ? 'text-[#0b6b5a]' : 'text-red-700'}`}>{integrity === 'ok' ? 'Pemeriksaan integritas: database sehat.' : 'Pemeriksaan integritas menemukan masalah.'}</p>}</section>
          <section id="backup" className="rounded border border-[#dce3de] bg-white p-4"><h2 className="text-lg font-bold">Backup &amp; Pemulihan</h2><p className="mt-3 text-xs font-semibold">Backup Terakhir</p><p className="mt-1 text-xs">{lastBackup ? `${new Date(lastBackup.createdAt).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta', dateStyle: 'medium', timeStyle: 'short' })} · ${size(lastBackup.bytes)}` : 'Belum ada backup'}</p>{lastBackup && <p className="mt-1 truncate font-mono text-[10px] text-[#667477]">{lastBackup.name}</p>}<button type="submit" formAction={backupAction} className="mt-4 flex items-center gap-2 rounded border border-[#0b6b5a] px-3 py-2 text-xs text-[#0b6b5a]"><Database size={15}/>Backup Sekarang</button>{backupSaved && <p role="status" className="mt-2 text-xs text-[#0b6b5a]">Backup database berhasil dibuat.</p>}</section></div>
        <div className="sticky bottom-0 z-20 col-span-full flex flex-wrap items-center justify-end gap-2 border-t border-[#dce3de] bg-white/95 px-3 py-3"><button type="reset" className="rounded border border-[#cbd6d1] px-4 py-2 text-xs">Batalkan Perubahan</button><button className="flex items-center gap-2 rounded bg-[#0b6b5a] px-5 py-2 text-xs font-semibold text-white"><Save size={15}/>Simpan Pengaturan</button></div></form></div></div>;
}
