import Link from 'next/link';
import Image from 'next/image';
import { and, desc, eq, isNull, like, or, sql } from 'drizzle-orm';
import { BookOpen, Camera, ChevronRight, Home, ImageIcon, MapPin, Search, SlidersHorizontal } from 'lucide-react';
import { db } from '@/db';
import { assets, exifMetadata, issues, locations, photos } from '@/db/schema';
import { GlobalSearchInput } from '@/components/GlobalSearchInput';

type Params = { q?: string; type?: string; from?: string; to?: string; camera?: string; location?: string; orientation?: string };
const href = (params: Record<string, string>) => `/search?${new URLSearchParams(Object.entries(params).filter(([, value]) => value))}`;
const photoDate = (date: Date | null) => date?.toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta', day: 'numeric', month: 'short', year: 'numeric' }) ?? 'Tanggal belum ada';
const outerIssueId = sql.raw('"issues"."id"');

export default async function GlobalSearchPage({ searchParams }: { searchParams: Promise<Params> }) {
  const query = await searchParams;
  const q = (query.q ?? '').trim().slice(0, 100);
  const type = ['all', 'photo', 'issue', 'location', 'date'].includes(query.type ?? '') ? query.type! : 'all';
  const from = /^\d{4}$/.test(query.from ?? '') ? query.from! : '';
  const to = /^\d{4}$/.test(query.to ?? '') ? query.to! : '';
  const camera = (query.camera ?? '').trim().slice(0, 80);
  const location = (query.location ?? '').trim().slice(0, 80);
  const orientation = ['landscape', 'portrait', 'square'].includes(query.orientation ?? '') ? query.orientation! : '';
  const terms = q.toLowerCase().split(/\s+/).filter(Boolean).slice(0, 8);
  const photoMatch = terms.length ? and(...terms.map(term => or(like(photos.filename, `%${term}%`), like(exifMetadata.camera, `%${term}%`), like(exifMetadata.lens, `%${term}%`), like(locations.label, `%${term}%`), sql`exists(select 1 from photo_tags pt join tags t on t.id = pt.tag_id where pt.photo_id = ${photos.id} and t.name like ${`%${term}%`})`, sql`exists(select 1 from issue_page_photos ipp where ipp.photo_id = ${photos.id} and (ipp.caption like ${`%${term}%`} or ipp.alt_text like ${`%${term}%`}))`, sql`strftime('%Y', ${photos.capturedAt}, 'unixepoch') like ${`%${term}%`}`))) : sql`1 = 0`;
  const photoFilter = and(isNull(photos.deletedAt), photoMatch, from ? sql`strftime('%Y', ${photos.capturedAt}, 'unixepoch') >= ${from}` : undefined, to ? sql`strftime('%Y', ${photos.capturedAt}, 'unixepoch') <= ${to}` : undefined, camera ? like(exifMetadata.camera, `%${camera}%`) : undefined, location ? like(locations.label, `%${location}%`) : undefined, orientation ? sql`exists(select 1 from assets original where original.photo_id = ${photos.id} and original.type = 'original' and ${sql.raw(orientation === 'landscape' ? 'original.width > original.height' : orientation === 'portrait' ? 'original.height > original.width' : 'original.width = original.height')})` : undefined);
  const photoRows = db.select({ id: photos.id, filename: photos.filename, capturedAt: photos.capturedAt, thumbnailId: assets.id, camera: exifMetadata.camera, location: locations.label }).from(photos).leftJoin(assets, and(eq(assets.photoId, photos.id), eq(assets.type, 'thumbnail'))).leftJoin(exifMetadata, eq(exifMetadata.photoId, photos.id)).leftJoin(locations, eq(locations.photoId, photos.id)).where(photoFilter).orderBy(desc(photos.capturedAt)).all();
  const issueMatch = terms.length ? and(...terms.map(term => or(like(issues.title, `%${term}%`), like(issues.subtitle, `%${term}%`), like(issues.description, `%${term}%`), sql`exists(select 1 from issue_pages ip join issue_page_photos ipp on ipp.page_id = ip.id where ip.issue_id = ${outerIssueId} and ipp.caption like ${`%${term}%`})`))) : sql`1 = 0`;
  const issueRows = db.select({ id: issues.id, code: issues.code, title: issues.title, subtitle: issues.subtitle, status: issues.status, publishedAt: issues.publishedAt, coverId: sql<string | null>`(select a.id from issue_pages ip join issue_page_photos ipp on ipp.page_id = ip.id join assets a on a.photo_id = ipp.photo_id and a.type = 'thumbnail' where ip.issue_id = ${outerIssueId} order by ip.page_number limit 1)` }).from(issues).where(issueMatch).orderBy(desc(issues.publishedAt)).limit(100).all();
  const placeMap = new Map<string, { label: string; count: number; thumbnailId: string | null }>();
  const dateMap = new Map<string, { label: string; count: number; thumbnailId: string | null }>();
  for (const photo of photoRows) {
    if (photo.location) { const previous = placeMap.get(photo.location); placeMap.set(photo.location, { label: photo.location, count: (previous?.count ?? 0) + 1, thumbnailId: previous?.thumbnailId ?? photo.thumbnailId }); }
    if (photo.capturedAt) { const label = photo.capturedAt.toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta', month: 'long', year: 'numeric' }); const previous = dateMap.get(label); dateMap.set(label, { label, count: (previous?.count ?? 0) + 1, thumbnailId: previous?.thumbnailId ?? photo.thumbnailId }); }
  }
  const places = [...placeMap.values()].sort((a, b) => b.count - a.count);
  const dates = [...dateMap.values()].sort((a, b) => b.count - a.count);
  const total = photoRows.length + issueRows.length + places.length + dates.length;
  const filters = { q, from, to, camera, location, orientation };
  const tabs = [{ key: 'all', label: 'Semua', count: total }, { key: 'photo', label: 'Foto', count: photoRows.length }, { key: 'issue', label: 'Issue', count: issueRows.length }, { key: 'location', label: 'Lokasi', count: places.length }, { key: 'date', label: 'Tanggal', count: dates.length }];

  return <div className="-mx-7 -mb-5 grid min-h-[calc(100dvh-88px)] grid-cols-1 bg-[#fffefa] xl:grid-cols-[minmax(0,1fr)_290px] max-sm:-mx-4"><main className="min-w-0 px-4 pb-8 pt-4 lg:px-7"><div className="flex items-center gap-2 border-b border-[#e0e5e2] pb-3 text-xs text-[#586a6c]"><Home size={15}/><ChevronRight size={14}/>Pencarian</div><h1 className="mt-4 font-serif text-[clamp(31px,2.8vw,45px)] font-bold leading-none">Pencarian Global</h1><p className="mt-1 text-sm text-[#667477]">Temukan foto, cerita, lokasi, dan momen dalam arsip Anda.</p><div className="mt-4"><GlobalSearchInput initialQuery={q}/></div>
      {q ? <><div className="mt-5"><h2 className="font-serif text-xl font-bold">Hasil untuk “{q}”</h2><p className="text-xs text-[#667477]">{total.toLocaleString('id-ID')} hasil pada data yang terindeks</p></div><div className="mt-3 flex gap-2 overflow-x-auto border-b border-[#e0e5e2]">{tabs.map(tab => <Link key={tab.key} href={href({ ...filters, type: tab.key })} className={`flex shrink-0 items-center gap-2 border-b-2 px-3 py-2 text-xs ${type === tab.key ? 'border-[#0c6c5c] font-semibold text-[#0a6556]' : 'border-transparent text-[#586a6c]'}`}>{tab.label}<span className="rounded-full bg-[#edf1ef] px-2 py-0.5 text-[10px]">{tab.count}</span></Link>)}</div>{(from || to || camera || location || orientation) && <div className="mt-2 flex flex-wrap items-center gap-2 text-xs">{[from || to ? `${from || 'Awal'}–${to || 'Kini'}` : '', camera, location, orientation].filter(Boolean).map(value => <span key={value} className="rounded-full bg-[#e9f2ee] px-3 py-1">{value}</span>)}<Link href={href({ q, type })} className="text-[#116a5c] underline">Hapus semua</Link></div>}
        {(type === 'all' || type === 'photo') && photoRows.length > 0 && <section className="mt-5"><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 font-serif text-xl font-bold"><ImageIcon size={19}/>Foto</h3>{type === 'all' && <Link href={href({ ...filters, type: 'photo' })} className="text-xs text-[#116a5c]">Lihat semua {photoRows.length} foto →</Link>}</div><div className="grid grid-cols-2 gap-2 md:grid-cols-3 2xl:grid-cols-6">{photoRows.slice(0, type === 'all' ? 6 : 60).map(photo => <Link key={photo.id} href={`/photos/${photo.id}`} className="min-w-0 overflow-hidden rounded border border-[#dfe6e2] bg-white hover:border-[#0b6b5a]"><div className="relative aspect-[1.4] bg-[#e8eeeb]">{photo.thumbnailId ? <Image src={`/api/assets/${photo.thumbnailId}`} alt="" fill unoptimized sizes="220px" className="object-cover grayscale"/> : <ImageIcon size={26} className="m-auto pt-8"/>}</div><div className="p-2 text-[11px]"><strong className="block truncate">{photo.filename}</strong><span className="block text-[#657579]">{photoDate(photo.capturedAt)}</span><span className="mt-1 flex items-center gap-1 truncate text-[#657579]"><MapPin size={11}/>{photo.location || 'Lokasi belum ada'}</span><span className="mt-1 flex items-center gap-1 truncate text-[#657579]"><Camera size={11}/>{photo.camera || 'Kamera belum ada'}</span></div></Link>)}</div></section>}
        {(type === 'all' || type === 'issue') && issueRows.length > 0 && <section className="mt-6"><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 font-serif text-xl font-bold"><BookOpen size={19}/>Issue</h3>{type === 'all' && <Link href={href({ ...filters, type: 'issue' })} className="text-xs text-[#116a5c]">Lihat semua {issueRows.length} issue →</Link>}</div><div className="grid gap-2 md:grid-cols-2">{issueRows.slice(0, type === 'all' ? 2 : 30).map(issue => <Link key={issue.id} href={`/issues/${issue.id}/preview`} className="flex min-w-0 gap-3 rounded border border-[#dfe6e2] bg-white p-2 hover:border-[#0b6b5a]"><div className="relative h-18 w-22 shrink-0 overflow-hidden bg-[#e8eeeb]">{issue.coverId && <Image src={`/api/assets/${issue.coverId}`} alt="" fill unoptimized sizes="90px" className="object-cover grayscale"/>}</div><div className="min-w-0"><strong className="block truncate font-serif text-sm">{issue.title}</strong><span className="text-[10px] text-[#657579]">{issue.status} · {issue.code}</span><p className="mt-1 line-clamp-2 text-xs text-[#657579]">{issue.subtitle || 'Cerita foto dalam arsip ChronoVista.'}</p></div></Link>)}</div></section>}
        {(type === 'all' || type === 'location' || type === 'date') && (places.length > 0 || dates.length > 0) && <div className="mt-6 grid gap-4 lg:grid-cols-2">{(type === 'all' || type === 'location') && places.length > 0 && <section><h3 className="mb-2 flex items-center gap-2 font-serif text-lg font-bold"><MapPin size={18}/>Lokasi</h3><div className="grid gap-2 sm:grid-cols-2">{places.slice(0, type === 'all' ? 3 : 24).map(place => <Link key={place.label} href={href({ q, location: place.label, type: 'photo' })} className="flex items-center gap-2 rounded border border-[#dfe6e2] bg-white p-2 text-xs"><MapPin size={15}/><span className="min-w-0 flex-1 truncate">{place.label}</span><span>{place.count} foto</span><ChevronRight size={14}/></Link>)}</div></section>}{(type === 'all' || type === 'date') && dates.length > 0 && <section><h3 className="mb-2 font-serif text-lg font-bold">Tanggal</h3><div className="grid gap-2 sm:grid-cols-2">{dates.slice(0, type === 'all' ? 3 : 24).map(item => <div key={item.label} className="flex items-center gap-2 rounded border border-[#dfe6e2] bg-white p-2 text-xs"><span className="min-w-0 flex-1 truncate">{item.label}</span><span>{item.count} foto</span></div>)}</div></section>}</div>}
        {total === 0 && <div className="mt-10 rounded border border-[#dfe6e2] bg-white py-16 text-center"><Search size={32} className="mx-auto text-[#91a49d]"/><h2 className="mt-3 font-serif text-lg font-bold">Tidak ada hasil</h2><p className="mt-1 text-sm text-[#657579]">Coba istilah atau filter yang lebih luas.</p></div>}</> : <div className="mt-10 rounded border border-[#dfe6e2] bg-white py-16 text-center"><Search size={32} className="mx-auto text-[#91a49d]"/><h2 className="mt-3 font-serif text-lg font-bold">Mulai pencarian</h2><p className="mt-1 text-sm text-[#657579]">Cari nama file, judul Issue, lokasi, kamera, atau tag.</p></div>}
    </main><aside className="border-t border-[#dfe6e2] bg-white p-4 xl:border-l xl:border-t-0"><form action="/search" className="rounded border border-[#dfe6e2] p-4"><input type="hidden" name="q" value={q}/><input type="hidden" name="type" value={type}/><h2 className="flex items-center gap-2 font-serif text-lg font-bold"><SlidersHorizontal size={17}/>Persempit Hasil</h2><div className="mt-4 border-t border-[#e4e9e6] pt-3"><label className="text-xs font-semibold">Rentang tahun</label><div className="mt-2 flex items-center gap-2"><input name="from" type="number" min="1900" max="2100" defaultValue={from} placeholder="Dari" aria-label="Tahun awal" className="w-full min-w-0 rounded border border-[#d1dad5] px-2 py-2 text-xs"/><span>–</span><input name="to" type="number" min="1900" max="2100" defaultValue={to} placeholder="Sampai" aria-label="Tahun akhir" className="w-full min-w-0 rounded border border-[#d1dad5] px-2 py-2 text-xs"/></div></div><label className="mt-4 block border-t border-[#e4e9e6] pt-3 text-xs font-semibold">Kamera<input name="camera" defaultValue={camera} placeholder="Semua kamera" className="mt-2 w-full rounded border border-[#d1dad5] px-2 py-2 text-xs font-normal"/></label><label className="mt-4 block border-t border-[#e4e9e6] pt-3 text-xs font-semibold">Lokasi<input name="location" defaultValue={location} placeholder="Semua lokasi" className="mt-2 w-full rounded border border-[#d1dad5] px-2 py-2 text-xs font-normal"/></label><label className="mt-4 block border-t border-[#e4e9e6] pt-3 text-xs font-semibold">Orientasi<select name="orientation" defaultValue={orientation} className="mt-2 w-full rounded border border-[#d1dad5] bg-white px-2 py-2 text-xs font-normal"><option value="">Semua orientasi</option><option value="landscape">Lanskap</option><option value="portrait">Potret</option><option value="square">Persegi</option></select></label><button className="mt-5 w-full rounded bg-[#0b6657] px-3 py-2.5 text-xs font-semibold text-white">Terapkan Filter</button></form><div className="mt-4 rounded border border-[#dfe6e2] p-4"><GlobalSearchInput initialQuery={q} mode="recent"/></div></aside></div>;
}
