'use client';

import Link from 'next/link';
import { useActionState } from 'react';
import { Aperture, ArrowRight, LockKeyhole, UserRound } from 'lucide-react';
import { loginAction } from './actions';

export default function LoginPage() {
  const [state, action, isPending] = useActionState(loginAction, null);
  return <main className="grid min-h-dvh lg:grid-cols-2 bg-[#faf9f5] text-[#18242a]">
    <div className="relative hidden min-h-dvh flex-col justify-between overflow-hidden bg-[#163f3b] p-12 text-white lg:flex"><Link href="/" className="flex items-center gap-3 text-2xl font-bold"><Aperture size={39}/>ChronoVista</Link><div className="relative z-10 max-w-xl"><p className="mb-5 font-mono text-xs tracking-[.3em] text-[#bad1c9]">FOTO · WAKTU · CERITA</p><h1 className="text-5xl font-bold leading-tight tracking-tight xl:text-6xl">Setiap foto punya waktunya. Setiap waktu punya cerita.</h1><p className="mt-6 max-w-md text-lg text-[#d8e5df]">Masuk ke ruang kerja untuk merawat arsip dan melanjutkan cerita fotografi Anda.</p></div><p className="relative z-10 font-mono text-xs tracking-[.2em] text-[#bad1c9]">MEREKAM HARI INI, UNTUK MASA DEPAN</p><div className="absolute -bottom-38 -right-30 h-140 w-140 rounded-full border border-white/15"/><div className="absolute -bottom-16 -right-10 h-90 w-90 rounded-full border border-white/15"/></div>
    <div className="flex min-h-dvh flex-col px-6 py-7 sm:px-12"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 font-bold lg:hidden"><Aperture size={29}/>ChronoVista</Link><Link href="/" className="ml-auto text-sm text-[#17675a] hover:underline">← Kembali ke beranda</Link></div><div className="mx-auto flex w-full max-w-md flex-1 flex-col justify-center py-10"><p className="mb-3 font-mono text-xs font-bold tracking-[.25em] text-[#17675a]">RUANG KERJA PERSONAL</p><h2 className="text-4xl font-extrabold tracking-tight sm:text-5xl">Selamat datang kembali.</h2><p className="mt-3 text-[#64747a]">Masuk untuk menjelajahi arsip Anda.</p><form action={action} className="mt-10 space-y-5"><div><label htmlFor="username" className="mb-2 block text-sm font-semibold">Username atau email</label><div className="relative"><UserRound size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#6c817e]"/><input id="username" name="username" type="text" autoComplete="username" required placeholder="Username" className="h-13 w-full rounded-md border border-[#cad5d0] bg-white pl-12 pr-4 outline-none focus-visible:ring-2 focus-visible:ring-[#176f60]"/></div></div><div><label htmlFor="password" className="mb-2 block text-sm font-semibold">Password</label><div className="relative"><LockKeyhole size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#6c817e]"/><input id="password" name="password" type="password" autoComplete="current-password" required placeholder="Masukkan password" className="h-13 w-full rounded-md border border-[#cad5d0] bg-white pl-12 pr-4 outline-none focus-visible:ring-2 focus-visible:ring-[#176f60]"/></div></div>{state?.error && <p role="alert" className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</p>}<button type="submit" disabled={isPending} className="flex h-13 w-full items-center justify-center gap-3 rounded-md bg-[#116a5c] font-semibold text-white hover:bg-[#0b554b] disabled:opacity-60">{isPending ? 'Memproses...' : 'Masuk ke Ruang Kerja'}<ArrowRight size={18}/></button></form><p className="mt-8 border-t border-[#d7ded9] pt-6 text-center text-sm text-[#71817f]">Arsip personal, tersimpan secara lokal.</p></div><p className="text-center font-mono text-[10px] tracking-[.15em] text-[#71817f]">© CHRONOVISTA · SETIAP FOTO PUNYA CERITA</p></div>
  </main>;
}
