import Link from 'next/link';
import { AlertTriangle, ArrowRight, BookOpen, Eye, FilePenLine, Globe2, ImageIcon, LockKeyhole, Plus, Search } from 'lucide-react';
import { db } from '@/db';
import { issues } from '@/db/schema';
import { and, count, desc, eq, like, or, sql } from 'drizzle-orm';

type SearchParams = { q?: string; status?: string; sort?: string; page?: string };
const outerIssueId = sql.raw('"issues"."id"');
const frameCount = sql<number>`(select count(*) from issue_page_photos ipp join issue_pages ip on ip.id = ipp.page_id where ip.issue_id = ${outerIssueId})`;
const coverId = sql<string | null>`(select a.id from issue_pages ip join issue_page_photos ipp on ipp.page_id = ip.id join assets a on a.photo_id = ipp.photo_id and a.type = 'thumbnail' where ip.issue_id = ${outerIssueId} order by ip.page_number limit 1)`;
export default async function IssuesPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const query = await searchParams;
  const q = (query.q ?? '').trim().slice(0, 100);
  const status = ['Draft', 'Published', 'Scheduled', 'Unpublished', 'Archived'].includes(query.status ?? '') ? query.status : '';
  const sort = query.sort === 'oldest' ? 'oldest' : 'newest';
  const page = Math.max(1, Math.min(1000, Number.parseInt(query.page ?? '1', 10) || 1));
  const stats = db.select({ status: issues.status, value: count() }).from(issues).groupBy(issues.status).all();
  const stat = (name: string) => stats.find(row => row.status === name)?.value ?? 0;
  const totalIssues = stats.reduce((sum, row) => sum + row.value, 0);
  const filter = and(q ? or(like(issues.title, `%${q}%`), like(issues.code, `%${q}%`)) : undefined, status ? eq(issues.status, status) : undefined);
  const total = db.select({ value: count() }).from(issues).where(filter).get()?.value ?? 0;
  const itemsQuery = db.select({ id: issues.id, code: issues.code, title: issues.title, subtitle: issues.subtitle, status: issues.status, visibility: issues.visibility, publishedAt: issues.publishedAt, frames: frameCount, coverId }).from(issues).where(filter).orderBy(sort === 'oldest' ? sql`cast(substr(${issues.code}, 4) as integer) asc` : sql`cast(substr(${issues.code}, 4) as integer) desc`).limit(6).offset((page - 1) * 6);
  const items = itemsQuery.all();
  const featured = db.select({ id: issues.id, code: issues.code, title: issues.title, subtitle: issues.subtitle, frames: frameCount, coverId }).from(issues).where(eq(issues.status, 'Draft')).orderBy(desc(sql`cast(substr(${issues.code}, 4) as integer)`)).limit(1).get();
  const pageHref = (number: number) => `/issues?${new URLSearchParams({ ...(q ? { q } : {}), ...(status ? { status } : {}), ...(sort !== 'newest' ? { sort } : {}), page: String(number) })}`;
  return <div className="mx-auto max-w-[1500px] space-y-5 pb-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight">Issue</h1><p className="text-[#65747a]">Susun foto menjadi satu cerita yang utuh.</p></div><Link href="/issues/new" className="flex items-center gap-2 rounded bg-[#116a5c] px-5 py-2.5 text-sm font-semibold text-white"><Plus size={20}/>Buat Issue Baru</Link></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ icon: BookOpen, value: totalIssues, label: 'Total Issue' }, { icon: Globe2, value: stat('Published'), label: 'Published' }, { icon: FilePenLine, value: stat('Draft'), label: 'Draft' }, { icon: AlertTriangle, value: stat('Unpublished'), label: 'Perlu Ditinjau' }].map(item => <div key={item.label} className="flex min-h-20 items-center gap-4 rounded-md border border-[#d9dfdc] bg-white px-5"><item.icon size={29} className="text-[#176b5d]" strokeWidth={1.6}/><div><strong className="block text-2xl leading-none">{item.value}</strong><span className="text-sm text-[#65747a]">{item.label}</span></div></div>)}</div>
    <form action="/issues" className="grid gap-2 lg:grid-cols-[minmax(200px,1fr)_170px_170px_auto]"><label className="relative"><span className="sr-only">Cari Issue</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#71817e]" size={18}/><input type="search" name="q" defaultValue={q} placeholder="Cari judul atau kode Issue..." className="h-10 w-full rounded border border-[#d7dfda] bg-white pl-9 pr-3 text-sm"/></label><select name="status" aria-label="Filter status" defaultValue={status} className="h-10 rounded border border-[#d7dfda] bg-white px-3 text-sm"><option value="">Semua status</option><option value="Draft">Draft</option><option value="Published">Published</option><option value="Scheduled">Scheduled</option><option value="Unpublished">Unpublished</option><option value="Archived">Archived</option></select><select name="sort" aria-label="Urutan Issue" defaultValue={sort} className="h-10 rounded border border-[#d7dfda] bg-white px-3 text-sm"><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select><button className="rounded bg-[#e5f2ec] px-5 text-sm font-semibold text-[#116a5c]">Terapkan</button></form>
    {featured && <section className="grid overflow-hidden rounded-md border border-[#d9dfdc] bg-white md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="flex min-h-48 items-center justify-center bg-[#e7ece9] md:min-h-58">{featured.coverId ? <img src={`/api/assets/${featured.coverId}`} alt="" className="h-full w-full object-cover grayscale"/> : <ImageIcon size={48} className="text-[#9aad9f]"/>}</div><div className="flex flex-col justify-between p-5"><div><span className="rounded bg-[#e5f2ec] px-2 py-1 text-xs font-semibold text-[#116a5c]">DRAFT TERBARU</span><p className="mt-3 text-sm text-[#65747a]">{featured.code}</p><h2 className="text-xl font-bold">{featured.title}</h2><p className="text-sm text-[#65747a]">{featured.subtitle || 'Cerita sedang disusun'}</p></div><div className="mt-5"><p className="text-sm">{featured.frames} frame tersusun</p><div className="mt-2 h-2 rounded bg-[#e3e8e5]"><div className="h-full rounded bg-[#116a5c]" style={{ width: `${Math.min(100, featured.frames / 36 * 100)}%` }}/></div><div className="mt-4 flex gap-2"><Link href={`/issues/${featured.id}/edit`} className="rounded bg-[#116a5c] px-4 py-2 text-sm text-white">Lanjutkan Menyusun</Link><Link href={`/issues/${featured.id}/preview`} className="flex items-center gap-1 rounded border border-[#b8c8c1] px-4 py-2 text-sm"><Eye size={16}/>Pratinjau</Link></div></div></div></section>}
    <div className="flex items-end gap-3"><h2 className="text-xl font-bold">Semua Issue</h2><span className="text-sm text-[#65747a]">{total} issue</span></div>
    {items.length ? <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{items.map(item => <article key={item.id} className="flex min-h-38 gap-3 rounded-md border border-[#d9dfdc] bg-white p-3"><div className="flex w-32 shrink-0 items-center justify-center overflow-hidden rounded bg-[#e7ece9]">{item.coverId ? <img src={`/api/assets/${item.coverId}`} alt="" loading="lazy" className="h-full w-full object-cover grayscale"/> : <ImageIcon size={32} className="text-[#9aad9f]"/>}</div><div className="flex min-w-0 flex-1 flex-col"><div className="flex items-start justify-between gap-2"><span className="text-xs text-[#65747a]">{item.code}</span><span className={`rounded px-2 py-0.5 text-[10px] ${item.status === 'Published' ? 'bg-[#e0f2e9] text-[#12685b]' : 'bg-[#eef0ef] text-[#63726e]'}`}>{item.status}</span></div><h3 className="mt-1 truncate font-bold">{item.title}</h3><p className="truncate text-xs text-[#65747a]">{item.subtitle || 'Belum ada subtitle'}</p><p className="mt-1 text-xs text-[#65747a]">{item.frames} frame</p><div className="mt-auto flex items-center gap-3 border-t border-[#e1e6e2] pt-2 text-xs"><Link href={`/issues/${item.id}/preview`} className="flex items-center gap-1 text-[#116a5c]"><Eye size={14}/>Buka</Link>{item.status === 'Draft' && <Link href={`/issues/${item.id}/edit`} className="flex items-center gap-1 text-[#116a5c]"><FilePenLine size={14}/>Edit</Link>}<span className="ml-auto flex items-center gap-1 text-[#65747a]">{item.visibility === 'Public' ? <Globe2 size={14}/> : <LockKeyhole size={14}/>} {item.visibility}</span></div></div></article>)}</div> : <div className="rounded-md border border-[#d9dfdc] bg-white py-16 text-center"><BookOpen size={42} className="mx-auto text-[#90a49e]"/><h2 className="mt-3 text-lg font-bold">Belum ada Issue</h2><p className="mt-2 text-sm text-[#65747a]">Mulai menyusun cerita dari foto di Arsip.</p><Link href="/issues/new" className="mt-4 inline-flex rounded bg-[#116a5c] px-5 py-2 text-sm text-white">Buat Issue Pertama</Link></div>}
    <div className="flex justify-between border-t border-[#d9dfdc] pt-3 text-sm"><span>Menampilkan {items.length ? `${(page - 1) * 6 + 1}–${(page - 1) * 6 + items.length}` : '0'} dari {total} issue</span><div className="flex gap-3">{page > 1 && <Link href={pageHref(page - 1)} className="text-[#116a5c] underline">Sebelumnya</Link>}{page * 6 < total && <Link href={pageHref(page + 1)} className="text-[#116a5c] underline">Berikutnya <ArrowRight size={14} className="inline"/></Link>}</div></div>
  </div>;
}
