import Link from 'next/link';
import { AlertTriangle, ArrowRight, BookOpen, Download, Eye, FilePenLine, Globe2, Grid2X2, ImageIcon, List, LockKeyhole, Plus, Search } from 'lucide-react';
import { db } from '@/db';
import { assets, issuePagePhotos, issuePages, issues } from '@/db/schema';
import { and, count, desc, eq, like, or, sql } from 'drizzle-orm';

type SearchParams = { q?: string; status?: string; year?: string; sort?: string; view?: string; page?: string };
const outerIssueId = sql.raw('"issues"."id"');
const frameCount = sql<number>`(select count(*) from issue_page_photos ipp join issue_pages ip on ip.id = ipp.page_id where ip.issue_id = ${outerIssueId})`;
const coverId = sql<string | null>`(select a.id from issue_pages ip join issue_page_photos ipp on ipp.page_id = ip.id join assets a on a.photo_id = ipp.photo_id and a.type = 'thumbnail' where ip.issue_id = ${outerIssueId} order by ip.page_number limit 1)`;
export default async function IssuesPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const query = await searchParams;
  const q = (query.q ?? '').trim().slice(0, 100);
  const status = ['Draft', 'Published', 'Scheduled', 'Unpublished', 'Archived'].includes(query.status ?? '') ? query.status : '';
  const year = /^20\d{2}$/.test(query.year ?? '') ? query.year! : '';
  const sort = query.sort === 'oldest' ? 'oldest' : 'newest';
  const view = query.view === 'list' ? 'list' : 'grid';
  const page = Math.max(1, Math.min(1000, Number.parseInt(query.page ?? '1', 10) || 1));
  const stats = db.select({ status: issues.status, value: count() }).from(issues).groupBy(issues.status).all();
  const stat = (name: string) => stats.find(row => row.status === name)?.value ?? 0;
  const totalIssues = stats.reduce((sum, row) => sum + row.value, 0);
  const years = db.select({ year: sql<string>`strftime('%Y', ${issues.publishedAt}, 'unixepoch')` }).from(issues).where(sql`${issues.publishedAt} is not null`).groupBy(sql`strftime('%Y', ${issues.publishedAt}, 'unixepoch')`).all().map(row => row.year).filter(Boolean);
  const filter = and(q ? or(like(issues.title, `%${q}%`), like(issues.code, `%${q}%`)) : undefined, status ? eq(issues.status, status) : undefined, year ? sql`strftime('%Y', ${issues.publishedAt}, 'unixepoch') = ${year}` : undefined);
  const total = db.select({ value: count() }).from(issues).where(filter).get()?.value ?? 0;
  const itemsQuery = db.select({ id: issues.id, code: issues.code, title: issues.title, subtitle: issues.subtitle, status: issues.status, visibility: issues.visibility, publishedAt: issues.publishedAt, frames: frameCount, coverId }).from(issues).where(filter).orderBy(sort === 'oldest' ? sql`cast(substr(${issues.code}, 4) as integer) asc` : sql`cast(substr(${issues.code}, 4) as integer) desc`).limit(6).offset((page - 1) * 6);
  const items = itemsQuery.all();
  const featured = db.select({ id: issues.id, code: issues.code, title: issues.title, subtitle: issues.subtitle, frames: frameCount, coverId }).from(issues).where(eq(issues.status, 'Draft')).orderBy(desc(sql`cast(substr(${issues.code}, 4) as integer)`)).limit(1).get();
  const featuredImages = featured ? db.select({ id: assets.id }).from(issuePages).innerJoin(issuePagePhotos, eq(issuePagePhotos.pageId, issuePages.id)).innerJoin(assets, and(eq(assets.photoId, issuePagePhotos.photoId), eq(assets.type, 'thumbnail'))).where(eq(issuePages.issueId, featured.id)).orderBy(issuePages.pageNumber, issuePagePhotos.position).limit(5).all() : [];
  const pageHref = (number: number, nextView = view) => `/issues?${new URLSearchParams({ ...(q ? { q } : {}), ...(status ? { status } : {}), ...(year ? { year } : {}), ...(sort !== 'newest' ? { sort } : {}), view: nextView, page: String(number) })}`;
  return <div className="mx-auto max-w-[1600px] space-y-4 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[34px] font-extrabold leading-none tracking-tight">Issue</h1><p className="mt-1 text-[#65747a]">Susun 36 foto menjadi satu cerita yang utuh.</p></div><Link href="/issues/new" className="flex h-11 items-center gap-2 rounded bg-[#076b5c] px-5 text-sm font-semibold text-white"><Plus size={20}/>Buat Issue Baru</Link></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ icon: BookOpen, value: totalIssues, label: 'Total Issue' }, { icon: Globe2, value: stat('Published'), label: 'Published' }, { icon: FilePenLine, value: stat('Draft'), label: 'Draft' }, { icon: AlertTriangle, value: stat('Unpublished'), label: 'Perlu Ditinjau' }].map(item => <div key={item.label} className="flex h-[78px] items-center gap-5 rounded-md border border-[#d9dfdc] bg-white px-5 shadow-sm"><item.icon size={36} className={item.label === 'Published' ? 'text-[#116a5c]' : 'text-[#172329]'} strokeWidth={1.5}/><div><strong className="block text-[25px] leading-none">{item.value}</strong><span className="mt-1 block text-sm text-[#65747a]">{item.label}</span></div></div>)}</div>
    <div className="flex flex-wrap gap-2"><form action="/issues" className="grid min-w-0 flex-1 gap-2 sm:grid-cols-[minmax(200px,1fr)_140px_140px_175px_auto]"><label className="relative"><span className="sr-only">Cari Issue</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#71817e]" size={18}/><input type="search" name="q" defaultValue={q} placeholder="Cari judul atau kode issue..." className="h-10 w-full rounded border border-[#d7dfda] bg-white pl-9 pr-3 text-sm"/></label><select name="status" aria-label="Filter status" defaultValue={status} className="h-10 rounded border border-[#d7dfda] bg-white px-3 text-sm"><option value="">Semua Status</option><option value="Draft">Draft</option><option value="Published">Published</option><option value="Scheduled">Scheduled</option><option value="Unpublished">Perlu Ditinjau</option><option value="Archived">Archived</option></select><select name="year" aria-label="Filter tahun" defaultValue={year} className="h-10 rounded border border-[#d7dfda] bg-white px-3 text-sm"><option value="">Semua Tahun</option>{years.map(value => <option key={value} value={value}>{value}</option>)}</select><select name="sort" aria-label="Urutan Issue" defaultValue={sort} className="h-10 rounded border border-[#d7dfda] bg-white px-3 text-sm"><option value="newest">Urutkan: Terbaru</option><option value="oldest">Urutkan: Terlama</option></select><input type="hidden" name="view" value={view}/><button className="rounded border border-[#116a5c] bg-[#e5f2ec] px-3 text-sm font-semibold text-[#116a5c]">Terapkan</button></form><div className="flex h-10 overflow-hidden rounded border border-[#d7dfda] bg-white"><Link href={pageHref(1, 'grid')} aria-label="Tampilan grid" className={`flex w-10 items-center justify-center ${view === 'grid' ? 'bg-[#dceee8] text-[#075f52]' : ''}`}><Grid2X2 size={18}/></Link><Link href={pageHref(1, 'list')} aria-label="Tampilan daftar" className={`flex w-10 items-center justify-center border-l border-[#d7dfda] ${view === 'list' ? 'bg-[#dceee8] text-[#075f52]' : ''}`}><List size={18}/></Link></div></div>
    {featured && <section className="grid overflow-hidden rounded-md border border-[#d9dfdc] bg-white shadow-sm lg:grid-cols-[1.2fr_.7fr_.65fr]"><div className="grid h-[215px] grid-cols-[1.25fr_1fr] gap-1 bg-[#e7ece9] p-2"><div className="relative row-span-2 overflow-hidden bg-[#d9e0dc]">{featuredImages[0] ? <img src={`/api/assets/${featuredImages[0].id}`} alt="" className="h-full w-full object-cover grayscale"/> : <ImageIcon size={48} className="m-auto mt-16 text-[#9aad9f]"/>}</div>{[1, 2].map(row => <div key={row} className="grid grid-cols-2 gap-1">{[row * 2 - 1, row * 2].map(index => <div key={index} className="relative overflow-hidden bg-[#d9e0dc]">{featuredImages[index] ? <img src={`/api/assets/${featuredImages[index].id}`} alt="" className="h-full w-full object-cover grayscale"/> : null}</div>)}</div>)}</div><div className="flex flex-col justify-center p-5"><span className="w-fit rounded bg-[#e5f2ec] px-2 py-1 text-xs font-semibold text-[#116a5c]">DRAFT TERBARU</span><p className="mt-2 text-sm text-[#65747a]">{featured.code}</p><h2 className="text-xl font-bold">{featured.title}</h2><p className="text-sm text-[#65747a]">{featured.subtitle || 'Cerita sedang disusun'}</p><div className="mt-5 flex items-center gap-2 text-xs"><span className="shrink-0">{featured.frames} dari 36 frame</span><div className="h-2 w-full rounded bg-[#e3e8e5]"><div className="h-full rounded bg-[#116a5c]" style={{ width: `${Math.min(100, featured.frames / 36 * 100)}%` }}/></div><span>{Math.min(100, Math.round(featured.frames / 36 * 100))}%</span></div></div><div className="flex flex-col justify-center gap-3 border-t border-[#e1e6e2] p-5 text-sm lg:border-l lg:border-t-0"><p>{Math.max(0, 36 - featured.frames)} foto lagi diperlukan</p><p className="text-[#116a5c]">✓ Urutan foto dapat ditinjau</p><p className="text-[#116a5c]">✓ Pengaturan privasi tersedia</p><div className="mt-2 flex gap-2"><Link href={`/issues/${featured.id}/edit`} className="flex-1 rounded bg-[#116a5c] px-3 py-2 text-center text-xs font-semibold text-white">Lanjutkan Menyusun</Link><Link href={`/issues/${featured.id}/preview`} className="flex items-center gap-1 rounded border border-[#b8c8c1] px-3 py-2 text-xs"><Eye size={16}/>Pratinjau</Link></div></div></section>}
    <div className="flex items-end gap-3"><h2 className="text-xl font-bold">Semua Issue</h2><span className="text-sm text-[#65747a]">{total} issue</span></div>
    {items.length ? <div className={`grid gap-3 ${view === 'grid' ? 'lg:grid-cols-2 xl:grid-cols-3' : 'grid-cols-1'}`}>{items.map(item => <article key={item.id} className="flex min-h-[142px] gap-3 rounded-md border border-[#d9dfdc] bg-white p-2 shadow-sm"><div className="flex w-[34%] max-w-[135px] shrink-0 items-center justify-center overflow-hidden rounded bg-[#e7ece9]">{item.coverId ? <img src={`/api/assets/${item.coverId}`} alt="" loading="lazy" className="h-full w-full object-cover grayscale"/> : <ImageIcon size={32} className="text-[#9aad9f]"/>}</div><div className="flex min-w-0 flex-1 flex-col py-1 pr-1"><div className="flex items-start justify-between gap-2"><span className="text-xs text-[#65747a]">{item.code}</span><span className={`rounded px-2 py-0.5 text-[11px] ${item.status === 'Published' ? 'bg-[#e0f2e9] text-[#12685b]' : item.status === 'Unpublished' ? 'bg-[#fff0d4] text-[#8b5c12]' : 'bg-[#eef0ef] text-[#63726e]'}`}>{item.status === 'Unpublished' ? 'Perlu Ditinjau' : item.status}</span></div><h3 className="mt-1 truncate text-sm font-bold">{item.title}</h3><p className="truncate text-xs text-[#65747a]">{item.subtitle || (item.publishedAt ? item.publishedAt.toLocaleDateString('id-ID', { timeZone: 'Asia/Jakarta', dateStyle: 'medium' }) : 'Belum terbit')}</p><p className="mt-1 text-xs text-[#65747a]">{item.frames} frame</p><div className="mt-auto flex items-center gap-3 border-t border-[#e1e6e2] pt-2 text-xs"><Link href={`/issues/${item.id}/preview`} className="flex items-center gap-1 hover:text-[#116a5c]"><Eye size={14}/>Buka</Link><a href={`/api/issues/${item.id}/pdf`} className="flex items-center gap-1 hover:text-[#116a5c]"><Download size={14}/>PDF</a><span className="ml-auto flex items-center gap-1 text-[#65747a]">{item.visibility === 'Public' ? <Globe2 size={14}/> : <LockKeyhole size={14}/>} {item.visibility === 'Public' ? 'Publik' : 'Privat'}</span></div></div></article>)}</div> : <div className="rounded-md border border-[#d9dfdc] bg-white py-16 text-center"><BookOpen size={42} className="mx-auto text-[#90a49e]"/><h2 className="mt-3 text-lg font-bold">Belum ada Issue</h2><p className="mt-2 text-sm text-[#65747a]">Mulai menyusun cerita dari foto di Arsip.</p><Link href="/issues/new" className="mt-4 inline-flex rounded bg-[#116a5c] px-5 py-2 text-sm text-white">Buat Issue Pertama</Link></div>}
    <div className="flex justify-between border-t border-[#d9dfdc] pt-3 text-sm"><span>Menampilkan {items.length ? `${(page - 1) * 6 + 1}–${(page - 1) * 6 + items.length}` : '0'} dari {total} issue</span><div className="flex gap-3">{page > 1 && <Link href={pageHref(page - 1)} className="text-[#116a5c] underline">Sebelumnya</Link>}{page * 6 < total && <Link href={pageHref(page + 1)} className="text-[#116a5c] underline">Berikutnya <ArrowRight size={14} className="inline"/></Link>}</div></div>
  </div>;
}
