import Link from 'next/link';
import { and, count, desc, eq, like, or, sql, sum } from 'drizzle-orm';
import { AlertTriangle, ArrowRight, BookOpen, ChevronLeft, ChevronRight, Database, FileText, Globe2, Grid2X2, House, ImageIcon, List, Pencil, Plus, Search } from 'lucide-react';
import { db } from '@/db';
import { assets, auditLogs, photoBooks } from '@/db/schema';
import { archivePhotoBookAction } from './actions';

type Query = { q?: string; status?: string; year?: string; sort?: string; view?: string; page?: string };
const outerBookId = sql.raw('"photo_books"."id"');
const pageCount = sql<number>`(select count(*) from book_pages bp where bp.book_id = ${outerBookId})`;
const coverId = sql<string | null>`(select a.id from assets a where a.photo_id = "photo_books"."cover_photo_id" and a.type = 'thumbnail' limit 1)`;

export default async function PhotoBooksPage({ searchParams }: { searchParams: Promise<Query> }) {
  const query = await searchParams;
  const q = (query.q ?? '').trim().slice(0, 100);
  const status = ['Draft', 'Published', 'Needs Review', 'Archived'].includes(query.status ?? '') ? query.status! : '';
  const year = /^\d{4}$/.test(query.year ?? '') ? Number(query.year) : null;
  const sort = query.sort === 'oldest' ? 'oldest' : 'newest';
  const view = query.view === 'list' ? 'list' : 'grid';
  const page = Math.max(1, Math.min(1000, Number(query.page) || 1));
  const stats = db.select({ status: photoBooks.status, total: count() }).from(photoBooks).groupBy(photoBooks.status).all();
  const stat = (name: string) => stats.find(item => item.status === name)?.total ?? 0;
  const totalBooks = stats.reduce((total, item) => total + item.total, 0);
  const years = db.select({ year: photoBooks.year }).from(photoBooks).groupBy(photoBooks.year).orderBy(desc(photoBooks.year)).all();
  const filter = and(q ? or(like(photoBooks.title, `%${q}%`), like(photoBooks.photographer, `%${q}%`)) : undefined, status ? eq(photoBooks.status, status) : undefined, year ? eq(photoBooks.year, year) : undefined);
  const total = db.select({ value: count() }).from(photoBooks).where(filter).get()?.value ?? 0;
  const items = db.select({ id: photoBooks.id, slug: photoBooks.slug, title: photoBooks.title, photographer: photoBooks.photographer, status: photoBooks.status, year: photoBooks.year, updatedAt: photoBooks.updatedAt, publishedAt: photoBooks.publishedAt, pages: pageCount, coverId }).from(photoBooks).where(filter).orderBy(sort === 'oldest' ? photoBooks.updatedAt : desc(photoBooks.updatedAt)).limit(6).offset((page - 1) * 6).all();
  const activity = db.select({ id: auditLogs.id, action: auditLogs.action, entityId: auditLogs.entityId, createdAt: auditLogs.createdAt }).from(auditLogs).where(eq(auditLogs.entityType, 'photo_book')).orderBy(desc(auditLogs.createdAt)).limit(3).all();
  const activityBooks = activity.length ? db.select({ id: photoBooks.id, title: photoBooks.title }).from(photoBooks).all() : [];
  const storage = db.select({ bytes: sum(assets.bytes) }).from(assets).get()?.bytes ?? '0';
  const usedGb = (Number(storage) / 1024 ** 3).toLocaleString('id-ID', { maximumFractionDigits: 1 });
  const href = (number: number, nextView = view) => `/photo-books?${new URLSearchParams({ ...(q ? { q } : {}), ...(status ? { status } : {}), ...(year ? { year: String(year) } : {}), sort, view: nextView, page: String(number) })}`;
  return <div className="-mx-7 -mb-5 grid min-h-[calc(100dvh-88px)] bg-[#fffefa] max-sm:-mx-4 xl:grid-cols-[minmax(0,1fr)_310px]">
    <div className="min-w-0 border-r border-[#e1e3df] px-5 pb-8 pt-2 lg:px-7"><div className="flex items-center gap-2 text-xs"><Link href="/dashboard"><House size={17}/></Link><ChevronRight size={14} className="text-[#7c8986]"/><span>Photo Book</span></div><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-[clamp(38px,4vw,54px)] leading-none">Photo Book</h1><p className="mt-1 text-base text-[#4e5b63]">Susun arsip foto menjadi buku visual yang utuh.</p></div><div className="flex gap-2"><Link href="/photo-books/templates" className="flex h-11 items-center gap-2 rounded border border-[#56646b] bg-white px-4 text-sm"><FileText size={18}/>Kelola Template</Link><Link href="/photo-books/new" className="flex h-11 items-center gap-2 rounded bg-[#075b4d] px-5 text-sm font-semibold text-white"><Plus size={20}/>Buat Photo Book</Link></div></div>
      <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ icon: BookOpen, total: totalBooks, label: 'Photo Book' }, { icon: Pencil, total: stat('Draft'), label: 'Draft' }, { icon: Globe2, total: stat('Published'), label: 'Dipublikasikan' }, { icon: AlertTriangle, total: stat('Needs Review'), label: 'Perlu Diperiksa' }].map(item => <div key={item.label} className="flex h-22 items-center gap-4 rounded border border-[#d7deda] bg-white px-5"><item.icon size={38} strokeWidth={1.5} className={item.label === 'Perlu Diperiksa' ? 'text-[#a75c18]' : 'text-[#0b5f50]'}/><div><strong className="block font-serif text-3xl leading-none">{item.total}</strong><span className="text-sm text-[#485962]">{item.label}</span></div></div>)}</div>
      <h2 className="mb-2 mt-6 font-serif text-2xl">Semua Photo Book</h2><div className="flex gap-2"><form action="/photo-books" className="grid min-w-0 flex-1 gap-2 sm:grid-cols-[minmax(170px,1fr)_140px_140px_155px_auto]"><label className="relative"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#64737c]"/><input name="q" type="search" defaultValue={q} placeholder="Cari judul atau fotografer..." className="h-11 w-full rounded border border-[#cbd4d2] bg-white pl-10 pr-2 text-sm"/></label><select name="status" defaultValue={status} aria-label="Status" className="rounded border border-[#cbd4d2] bg-white px-2 text-sm"><option value="">Semua Status</option><option>Draft</option><option value="Published">Dipublikasikan</option><option value="Needs Review">Perlu Diperiksa</option><option value="Archived">Diarsipkan</option></select><select name="year" defaultValue={year ?? ''} aria-label="Tahun" className="rounded border border-[#cbd4d2] bg-white px-2 text-sm"><option value="">Semua Tahun</option>{years.map(item => <option key={item.year}>{item.year}</option>)}</select><select name="sort" defaultValue={sort} aria-label="Urutan" className="rounded border border-[#cbd4d2] bg-white px-2 text-sm"><option value="newest">Terakhir Diubah</option><option value="oldest">Terlama Diubah</option></select><input type="hidden" name="view" value={view}/><button className="rounded border border-[#0b5f50] px-3 text-sm text-[#0b5f50]">Terapkan</button></form><div className="flex overflow-hidden rounded border border-[#cbd4d2]"><Link href={href(1, 'grid')} aria-label="Grid" className={`grid w-11 place-items-center ${view === 'grid' ? 'bg-[#075b4d] text-white' : 'bg-white'}`}><Grid2X2 size={19}/></Link><Link href={href(1, 'list')} aria-label="Daftar" className={`grid w-11 place-items-center border-l border-[#cbd4d2] ${view === 'list' ? 'bg-[#075b4d] text-white' : 'bg-white'}`}><List size={19}/></Link></div></div>
      {items.length ? <div className={`mt-4 grid gap-3 ${view === 'grid' ? 'lg:grid-cols-2' : 'grid-cols-1'}`}>{items.map(item => <article key={item.id} className="flex min-h-48 gap-4 rounded border border-[#d7deda] bg-white p-3"><div className="w-28 shrink-0 overflow-hidden rounded bg-[#e5e9e6] sm:w-32">{item.coverId ? <img src={`/api/assets/${item.coverId}`} alt="" className="h-full w-full object-cover grayscale"/> : <div className="grid h-full place-items-center"><ImageIcon size={32} className="text-[#91a19a]"/></div>}</div><div className="flex min-w-0 flex-1 flex-col"><h3 className="font-serif text-lg font-semibold leading-5">{item.title}</h3><span className={`mt-2 w-fit rounded-full px-3 py-1 text-xs ${item.status === 'Published' ? 'bg-[#ddf2e9] text-[#075b4d]' : item.status === 'Needs Review' ? 'bg-[#fff1db] text-[#9b561d]' : 'bg-[#edf0ef]'}`}>{item.status === 'Published' ? 'Dipublikasikan' : item.status === 'Needs Review' ? 'Perlu Diperiksa' : item.status}</span><p className="mt-3 text-xs text-[#58666e]">{item.pages} halaman · {item.status === 'Published' ? item.publishedAt?.toLocaleDateString('id-ID', { dateStyle: 'medium', timeZone: 'Asia/Jakarta' }) : `Diedit ${item.updatedAt.toLocaleDateString('id-ID', { dateStyle: 'medium', timeZone: 'Asia/Jakarta' })}`}</p><div className="mt-auto flex flex-wrap items-center gap-2 pt-3 text-xs"><Link href={`/photo-books/${item.id}/edit`} className="rounded bg-[#075b4d] px-3 py-2 text-white">{item.status === 'Draft' ? 'Lanjutkan Edit' : 'Buka'}</Link><Link href={`/photo-books/${item.id}/preview`} className="rounded border border-[#bccac4] px-3 py-2">Preview</Link><details className="relative"><summary className="cursor-pointer list-none rounded border border-[#bccac4] px-3 py-2" aria-label={`Aksi ${item.title}`}>•••</summary><div className="absolute bottom-full right-0 z-10 mb-1 min-w-36 rounded border border-[#bccac4] bg-white p-2 shadow-lg"><a href={`/api/photo-books/${item.id}/pdf`} className="block p-2 hover:bg-[#edf3ef]">Unduh PDF</a>{item.status === 'Published' && <Link href={`/books/${item.slug}`} className="block p-2 hover:bg-[#edf3ef]">Lihat Publik</Link>}<form action={archivePhotoBookAction.bind(null, item.id)}><button className="w-full p-2 text-left hover:bg-[#edf3ef]">Arsipkan</button></form></div></details></div></div></article>)}</div> : <div className="mt-4 rounded border border-[#d7deda] bg-white px-5 py-15 text-center"><BookOpen size={38} className="mx-auto text-[#77958a]"/><h3 className="mt-3 font-serif text-xl">Belum ada Photo Book</h3><p className="mt-2 text-sm text-[#58666e]">Buat buku dari foto arsip atau dari Issue yang sudah disusun.</p><Link href="/photo-books/new" className="mt-4 inline-flex rounded bg-[#075b4d] px-4 py-2 text-sm text-white">Buat Photo Book</Link></div>}
      <div className="mt-6 flex items-center justify-between text-sm"><span>{total ? `${(page - 1) * 6 + 1}–${(page - 1) * 6 + items.length}` : '0'} dari {total} Photo Book</span><div className="flex gap-2"><Link aria-disabled={page <= 1} href={page > 1 ? href(page - 1) : href(page)} className="rounded border border-[#cbd4d2] p-2"><ChevronLeft size={16}/></Link><span className="rounded bg-[#075b4d] px-3 py-2 text-white">{page}</span><Link aria-disabled={page * 6 >= total} href={page * 6 < total ? href(page + 1) : href(page)} className="rounded border border-[#cbd4d2] p-2"><ChevronRight size={16}/></Link></div></div>
    </div><aside className="space-y-4 px-5 py-6"><section className="rounded border border-[#d7deda] bg-white p-4"><h2 className="font-serif text-xl">Aktivitas Terbaru</h2>{activity.length ? <div className="mt-3 divide-y divide-[#e1e7e3]">{activity.map(item => <div key={item.id} className="flex gap-3 py-3"><FileText size={22} className="shrink-0"/><p className="text-sm"><strong className="block">{item.action === 'photo_book_published' ? 'Photo Book dipublikasikan' : item.action === 'photo_book_saved' ? 'Draft disimpan' : 'Photo Book dibuat'}</strong><span className="block text-[#56646b]">{activityBooks.find(book => book.id === item.entityId)?.title || 'Photo Book'}</span><small className="text-[#68777c]">{item.createdAt.toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Jakarta' })}</small></p></div>)}</div> : <p className="mt-4 text-sm text-[#647179]">Belum ada aktivitas Photo Book.</p>}</section><section className="rounded border border-[#d7deda] bg-white p-4"><h2 className="font-serif text-xl">Penyimpanan</h2><div className="mt-5 flex items-center gap-4"><Database size={32}/><div><strong>{usedGb} GB</strong> digunakan</div></div><div className="mt-3 h-2 rounded-full bg-[#e5e7e8]"><div className="h-full max-w-full rounded-full bg-[#075b4d]" style={{ width: `${Math.min(100, Number(storage) / (50 * 1024 ** 3) * 100)}%` }}/></div><p className="mt-2 text-xs text-[#68777c]">SQLite · Media arsip lokal</p></section><section className="rounded border border-[#d7deda] bg-white p-4"><h2 className="font-serif text-xl">Mulai Cepat</h2><div className="mt-3 space-y-2 text-sm"><Link href="/photo-books/templates" className="flex justify-between py-2">Gunakan template <ArrowRight size={16}/></Link><Link href="/photo-books/new?source=issue" className="flex justify-between py-2">Import dari Issue <ArrowRight size={16}/></Link><Link href="/photo-books/new" className="flex justify-between py-2">Buat dari arsip <ArrowRight size={16}/></Link></div></section></aside>
  </div>;
}
